### ISSUE TITLE
Idle timer?

### ISSUE THREAD

**Issue by dude2k5** [jneilliii/OctoPrint-TPLinkSmartplug#100]
Any chance you could add an idle timer or something similar? I leave prints at work and they finish when im at home, but sometimes other people use the machine after me, so I dont want to put a M code to shut it down every time. However if there was an idle timer that could detect if the printer was in "operational or error/disconnected" and turn off after 30 min of "idle", if it's still in this mode (without any interaction), that would be awesome. Pretty cool plugin regardless. I like.

**Comment by jneilliii** [comment]
If you enable the warn while printing option, the gcode triggers will be ignored and any ongoing print will not be interrupted.

**Comment by jneilliii** [comment]
If I remember correctly...

**Comment by jneilliii** [comment]
I know this issue has been closed for some time, but I just pushed updates to my current development branch the enables an idle timeout option. You can install using the URL below in plugin manager.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.19.zip
