### ISSUE TITLE
update to last version

### ISSUE THREAD

**Issue by mauwl** [jneilliii/OctoPrint-TPLinkSmartplug#108]
I updated to the latest version of tplinksmartplug and now the button close in octoprint no longer works.

By disabling tplinksmartplug the button close works again and if I reactivate the plugin, it does not work again

**Comment by jneilliii** [comment]
What button are you talking about?

**Comment by mauwl** [comment]
in all menu same problem 
![1](https://user-images.githubusercontent.com/50805589/57986948-84421480-7a7b-11e9-8e4a-849d9201ac9e.jpg)

**Comment by jneilliii** [comment]
That's weird, my code shouldn't effect that.  I wonder if something is getting broken due to upgrade and therefore breaking something else.  Could you try to ssh to your pi and run the following command?
```
nano ~/.octoprint/config.yaml
```
In that file, delete the entire tplinksmartplug section under plugins and save the file and then restart octoprint. You'll have to re-add your plug(s) back in.

**Comment by rrauenza** [comment]
Ok, maybe unrelated -- but tonight I kept having the edit screens disappear while editing fields -- like the countdown field:

![image](https://user-images.githubusercontent.com/1376251/58000850-dd677380-7a8e-11e9-8319-2b9acd086653.png)

I'd do a screen record, but I need a screen recorder that shows keystrokes.  I reproduced it once more, and then can't again.  I keep thinking I hit ESC but that key is far away from the keys I'm hitting.  Or its a keyboard glitch.

But if you see it, you're not going crazy.  If it never happens for you, then I'm going crazy.

**Comment by mauwl** [comment]
hi,
i delete all line tplinksmartplug in the yaml, i restart octoprint and add again plugin , but problem come again

but, i resolve this problem, i uninstall plugin and take previous version 0.9.13 and no more problem

**Comment by jneilliii** [comment]
@mauwl, I'll try to take a look this weekend.  For reference, which Themeify variant are you using and what other plugins are installed?  There could be a conflict from that perspective as well.

**Comment by hankchillx** [comment]
@jneilliii I am experiencing the same issue, I believe it may have something to do with the thermal runaway monitoring options, as when it's enabled and values are set, they disappear after a refresh. Something seems to be looking for them as an error appears in the console.

![image](https://user-images.githubusercontent.com/40478741/58247532-eb83f100-7d27-11e9-8a43-bf6e76101dc5.png)

**Comment by jneilliii** [comment]
Thanks for the details @hankchillx, I'll keep that in mind when I start investigating this weekend.

**Comment by mauwl** [comment]
hi, here what plugin i have
![plugin](https://user-images.githubusercontent.com/50805589/58286787-cdfa6a00-7daf-11e9-9468-648810492fdf.jpg)
