### ISSUE TITLE
General settings pane not showing

### ISSUE THREAD

**Issue by GeekDad63** [jneilliii/OctoPrint-TPLinkSmartplug#11]
General settings have disappeared after initial setup. 
[octoprint.log.zip](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/1308622/octoprint.log.zip)

**Comment by jneilliii** [comment]
Thanks for that.  I definitely see where it's loading the plugin.  What browser are you using? If there's a developer mode of some sort it would be helpful to see the console log to determine if there are any javascript errors.

**Comment by jneilliii** [comment]
Closing due to non-response.
