### ISSUE TITLE
plug to graph (blank)

### ISSUE THREAD

**Issue by mentaluproar** [jneilliii/OctoPrint-TPLinkSmartplug#114]
I have a 2 outlet tplink plug.  I tried using the graph function, but where it asks which plug to graph, there is nothing to select.

**Comment by jneilliii** [comment]
What's the model number? I don't the 2 plug units have energy monitoring.

**Comment by mentaluproar** [comment]
HS107

**Comment by jneilliii** [comment]
Yeah, I have one of those devices as well and it doesn't support energy monitoring.  The HS300 strip does.
