### ISSUE TITLE
Problem with refresh button and graph select

### ISSUE THREAD

**Issue by devildant** [jneilliii/OctoPrint-TPLinkSmartplug#115]
Hello,
for no apparent reason, the refresh button is disabled when loading the page (with the plug activated)
In addition, the chart does not have a listing in this list.
the reason for this malfunction is:
```
"err_code" in item.emeter.get_realtime
```
inside filteredSmartplugs and allPlugsDisabled

**Comment by devildant** [comment]
i try to uninstall/install (with clean inside config.yaml and remove db file)
![image](https://user-images.githubusercontent.com/8700106/58766910-bdeb4300-8584-11e9-8d56-32e031817d41.png)

**Comment by jneilliii** [comment]
Can you try this version for me?

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.17.zip

**Comment by devildant** [comment]
hello, i tried, but i have an error when il click on plug icon (for turn on or turn off)

```
2019-07-07 10:57:50,714 - octoprint.server.api - ERROR - Error while excuting SimpleApiPlugin tplinksmartplug
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 104, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tplinksmartplug/__init__.py", line 283, in on_api_command
    response = self.turn_off("{ip}".format(**data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tplinksmartplug/__init__.py", line 173, in turn_off
    plug_ip, plug_num = plugip.split("/")
ValueError: need more than 1 value to unpack

```

**Comment by jneilliii** [comment]
Try the same branch again for me @devildant.  That code was added by someone else and I think I just fixed it. I believe the issue was when you ran into a non energy monitoring plug.

**Comment by devildant** [comment]
it's better but the following bugs:
1) turn on printer, refresh octoprint page, the button refresh is disable
![image](https://user-images.githubusercontent.com/8700106/61087535-2fe16280-a436-11e9-8119-4800bd974c2d.png)

2) the graph select is empty
![image](https://user-images.githubusercontent.com/8700106/61087576-4ab3d700-a436-11e9-8208-da7acad09697.png)

sorry for the response time I have problems with internet :(

**Comment by jneilliii** [comment]
Weird.  I'm not able to reproduce on my end.  Do you only have the one HS110 plug?  I might be getting different results having multiple plugs configured and can do some additional testing.  Are there any errors in octoprint.log or the browser's console?

**Comment by devildant** [comment]
hello, 
yes only one HS110.
no i don't have error inside octoprint.log and browser console

**Comment by Tronnic** [comment]
Hello, I have a somewhat related problem. I don't see any power consumption at all (HS110) and the dropdown from the graphs menu is empty as well. 

![tpl1](https://user-images.githubusercontent.com/2569173/61585180-5306c300-ab56-11e9-8017-10750dd4dc77.PNG)
![tpl2](https://user-images.githubusercontent.com/2569173/61585181-5306c300-ab56-11e9-8edb-bfdd7dd931a8.PNG)

**Comment by RcTomcat1** [comment]
I have the same problem.
The power consumption widget is not even visible on my octoprint page, plug to graph is empty and nothing is selectable

**Comment by schmitzCatz** [comment]
Hi,
i can confirm this problem:
* HS110(Firmware 1.5.4, Hardware Version 2.0)
* Octoprint Version 1.3.12
* TP-Link Smartplug Version 0.9.17

**Comment by jneilliii** [comment]
What about if you enable polling? With debug logging enabled and polling enabled to 1 minute restart octoprint. Force a refresh on your browser by pressing ctrl + f5 (assuming windows) at the same time. Check your browser console for errors. After a couple of minutes to give the plugin plenty of time to poll check octoprint.log and the plugin log for errors. Upload them here for analysis, etc.

**Comment by schmitzCatz** [comment]
Hi,

works like a charm. Polling is enabled and after restarting octoprint the plugin is working as intended.

Thank you for your fast replay!
