### ISSUE TITLE
Second Plug Causes Error

### ISSUE THREAD

**Issue by Zexxen-Zalos** [jneilliii/OctoPrint-TPLinkSmartplug#116]
I have an HS100 for my printer and a HS105 for an AC bed. I've tested the HS105 by itself and it works fine with this plugin. However if I turn the HS105 on or off when the HS100 is on and the raspberry pi is connected to the printer, this error shows up in the terminal:
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2739
Please see https://faq.octoprint.org/serialerror for possible reasons of this.
Changing monitoring state from "Operational" to "Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2739)"
Connection closed, closing down monitor

I've also included the octoprint log below.
[octoprint.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3412472/octoprint.log)

**Comment by Zexxen-Zalos** [comment]
Here are my settings and the debug log as well.
[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3412598/plugin_tplinksmartplug_debug.log)
![HS105 Settings](https://user-images.githubusercontent.com/53097385/61563351-ae935c80-aa41-11e9-8bfc-c146be315f81.png)
![HS100 Settings](https://user-images.githubusercontent.com/53097385/61563352-ae935c80-aa41-11e9-9d71-a7f42c36112a.png)
![Smartplug Settings](https://user-images.githubusercontent.com/53097385/61563353-ae935c80-aa41-11e9-801b-a3d31d9667bb.png)

**Comment by jneilliii** [comment]
That's odd.  I have a similar setup in my home without any issues, although I don't use it for an AC heater pad but a light.  Does the same thing happen if only this plugin is enabled?

**Comment by Zexxen-Zalos** [comment]
I'm not sure. I've been messing around trying to see if a specific plugin I added is conflicting but I cant get it to occur consistently. However, when the error does occur it's always immediately (to the point that its simultaneous) after the HS105 comes on or turns off.

**Comment by Zexxen-Zalos** [comment]
So I've tried it with each plugin disabled aside from the ones that are in octoprint by default and I still am able to replicate the error

**Comment by jneilliii** [comment]
What about changing the settings of the plugs? Thermal runaway is a fairly new feature that I don't use personally, for example. If you disable all the options for both plugs and restart octoprint dries it still occur?

**Comment by Zexxen-Zalos** [comment]
It still occurs even if all settings are disabled.
