### ISSUE TITLE
HS300

### ISSUE THREAD

**Issue by mrstolpe** [jneilliii/OctoPrint-TPLinkSmartplug#129]
I just got the HS300 TP-Link/Kasa Smart Plug power strip. I was wondering if you could update your plugin to support it.

It is really useful, has built in power usage monitoring, also would allow me to control my heater and enclosure that I built.

It has 6 plugs that are controllable, also has a built in 3 port USB power output. 

Thank you.

**Comment by jneilliii** [comment]
It already does. You just have to enter the IP a special way.
