### ISSUE TITLE
Plugin unable to connect to my Tapo Smart Plug

### ISSUE THREAD

**Issue by bellini13** [jneilliii/OctoPrint-TPLinkSmartplug#135]
I purchased this smart plug, since it says it is TP-Link.  
https://www.amazon.com/gp/product/B07ZQYVXH8

I was able to setup and turn on/off the smart plug from the Tapo application.  I confirmed the IP address of the Tapo smart plug using my router and the Tapo app, which is 192.168.1.152

I also can ping 192.168.1.152 from my computer.

I configured the plugin to use the IP address, however it appears the TPLinkSmartplug is unable to communicate with the smart plug.  Below is the log file

[2020-01-19 17:17:27,760] DEBUG: OPERATIONAL
[2020-01-19 17:18:07,545] DEBUG: Checking status of 192.168.1.152.
[2020-01-19 17:18:07,546] DEBUG: {'system': {'get_sysinfo': {}}}
[2020-01-19 17:18:07,548] DEBUG: IP 192.168.1.152 is valid.
[2020-01-19 17:18:07,548] DEBUG: Sending command {'system': {'get_sysinfo': {}}} to 192.168.1.152
[2020-01-19 17:18:07,652] DEBUG: Could not connect to 192.168.1.152.
[2020-01-19 17:18:07,653] DEBUG: 
[2020-01-19 17:18:07,653] DEBUG: {'emeter': {'err_code': True}, 'system': {'get_sysinfo': {'relay_state': 3}}}

Anything I am missing?

**Comment by bellini13** [comment]
also to add, i connected to octopi using SSH, and confirmed that I can ping 192.168.1.152

running this command, returns "Cound not connect to host 192.168.1.152:9999"
./tplink_smartplug.py -t 192.168.1.152 -c info

Telnet connection refused...
telnet 192.168.1.152 9999
Trying 192.168.1.152...
telnet: Unable to connect to remote host: Connection refused

The octopi and smartplug are connected to the same wifi, and I do not have any

**Comment by jneilliii** [comment]
Previously discussed, the tapo devices aren't compatible and originally never will be. 

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/131

**Comment by bellini13** [comment]
I see.  So how do i determine what are compatible devices?

**Comment by jneilliii** [comment]
That's hard to say for sure. I know that the HS100, HS107, HS110, HS300 all work. My assumption is that any kasa smart plug device is compatible.

**Comment by bellini13** [comment]
I see what I did wrong.  I first tried to order this product, the HS100
https://www.amazon.com/gp/product/B0178IC734/

Saw there was a cheaper new mini size option, which was the Tapo but did not realize it was not an HS100

I ordered the HS100 to give that a try, thansk for your assistance!
