### ISSUE TITLE
TPLink stopped working

### ISSUE THREAD

**Issue by santanig5** [jneilliii/OctoPrint-TPLinkSmartplug#136]

**Comment by santanig5** [comment]
Greetings,
As of this morning TPLink is grey and does not control the plug. I have verified the reserved IP address of the plug is the same, can control it with the Kasa app and google home, but Octoprint can no longer turn off the printer at the end of a print.

**Comment by jneilliii** [comment]
Any errors in log?

**Comment by santanig5** [comment]
Please tell me how to check

Gary J. Santaniello
Sent from my iPad

On Jan 20, 2020, at 6:15 PM, jneilliii <notifications@github.com> wrote:

﻿

Any errors in log?

**Comment by jneilliii** [comment]
In the plugin's settings, enable the debug logging option and then restart OctoPrint.  Then once the web interface comes back up, try to check the status of the tplink and then in OctoPrint settings under the logging section download the plugin_tplinksmartplug_debug.log file.

**Comment by santanig5** [comment]
Per your request

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by santanig5** [comment]
Hello again,
The issue was totally on my side, even though I could manage the plug via the app, I could not see it on my network.
I had to remove the plug from the app, remove the reservation and re-add the plug and reservation and it is now pingable and controllable via octoprint.
It did take an update so I don’t know if that had any affect on the network settings.
Thanks for your time, sorry to trouble you .

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
