### ISSUE TITLE
Would be good to explicitly list the devices this works with 

### ISSUE THREAD

**Issue by FredericG-BE** [jneilliii/OctoPrint-TPLinkSmartplug#137]
It seems this plugin only works with a subset of devices That TP-Link calls "Smart Plugs". Would be good to mention the list of devices this plugin works with on the help-page. 
In a closed issue here I have found "HS100, HS107, HS110, HS300 all work. My assumption is that any kasa smart plug device is compatible."

I have a DSP-W115 and the the connection with the device fails. I works with the "mydlink" app.

**Comment by jneilliii** [comment]
I agree I should add this, but your plug isn't even a tplink why would you think it worked with a d-link device?

**Comment by FredericG-BE** [comment]
Indeed, I seem to have confused TP-link and D-link...! Sorry for that
