### ISSUE TITLE
Add request timeout

### ISSUE THREAD

**Issue by LilTrublMakr** [jneilliii/OctoPrint-TPLinkSmartplug#140]
I'll admit, I have only been playing with this for a couple of hours. I have been finding that sending commands has been somewhat unreliable. When I fist load up Octoprint, the icons will be grey. I click on them and they get the status. I can usually start my printer fine while using the button but sometimes it just keeps spinning. Same but way more often with the 2nd plug I have added that controls my LED lights.

Would it be possible to add a timeout function (maybe 15-30 seconds) that will stop the current action and maybe try and poll the plug to see what state it is in?

**Comment by jneilliii** [comment]
Added **Automatic Power Off** toggle in sidebar with cancel timer in my latest 0.9.18 branch. Adds settings to configure timer, remember toggle state, and `Off on Print Complete` within each plug's individual settings. If you start another print with the toggle enabled the power off will be cancelled automatically. If you want to test prior to release you can use the URL below in plugin manager.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.18.zip

Let me know your thoughts.
