### ISSUE TITLE
Don't show the graph tab if no power monitoring plugs are available

### ISSUE THREAD

**Issue by editter** [jneilliii/OctoPrint-TPLinkSmartplug#145]
My plug (HS100) doesn't have power monitoring so the tab that shows the graph will always be empty for me.  If there isn't any power monitoring can that tab be hidden?

**Comment by jneilliii** [comment]
I think that's possible. I'll try.

**Comment by jneilliii** [comment]
Just pushed an update to the next dev branch for version 0.9.19.  You can install from the URL below in plugin manager. Make sure to force a reload of the page if not prompted. Either ctrl+f5 or shift+f5 depending on your browser.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.19.zip

**Comment by editter** [comment]
Thanks, I tested it out and it works as expected!
