### ISSUE TITLE
Turn ON/OFF from discord command

### ISSUE THREAD

**Issue by markp89** [jneilliii/OctoPrint-TPLinkSmartplug#147]
I'm currently using your plugin perfectly from the Octoprint webpage but I'm looking to be able to use it from the discord bot plugin.

I am able to use /systemcommand from the discord bot but I'm not sure what command I can use to turn the TPLink plug on or off.

I guess I just need to the know the command that the ON/OFF button is using on the top header of the octoprint webpage?

**Comment by jneilliii** [comment]
Sorry, don't use discord personally, so not really sure. I suppose you could use a curl system command to make the api call to the plugin to power on/off. These are the commands that you would use to send the api calls, assuming that the discord bot plugin runs the command local to the pi.

ON
```
curl --insecure --silent --header "Content-Type: application/json" --header "X-Api-Key: <put your api key here>" --request POST --data-binary '{"command":"turnOn","ip":"192.168.0.130"}' "http://localhost:5000/api/plugin/tplinksmartplug"
```
OFF
```
curl --insecure --silent --header "Content-Type: application/json" --header "X-Api-Key: <put your api key here>" --request POST --data-binary '{"command":"turnOff","ip":"192.168.0.130"}' "http://localhost:5000/api/plugin/tplinksmartplug"

```
