### ISSUE TITLE
Icon not updating correctly anymore

### ISSUE THREAD

**Issue by Jackjan4** [jneilliii/OctoPrint-TPLinkSmartplug#148]
Hi,

since the new update the topbar icon is not updating correctly anymore. When a print is done and the plug is shut off by GCODE the icons stays green even if the plug was turned off, and vice versa.
Before the update it always worked flawlessly.

**Comment by jneilliii** [comment]
Quick question. If you press the refresh icon in the sidebar does thre status correct itself?

**Comment by Jackjan4** [comment]
Yes, the status icon corrects itself after clicking the refresh button.

**Comment by jneilliii** [comment]
Perfect, thanks. I'll check into this.

**Comment by jneilliii** [comment]
I've staged the next release and would appreciate if you could test it before me prior to maing it public.  Install using the URL below in plugin manager to upgrade.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.19.zip

**Comment by Jackjan4** [comment]
I tested it now and it works again. Thanks very much :)

**Comment by HuguesDug** [comment]
Hello
Problem was also present on my configuration a year ago or so.
Then, via the update, it got corrected.
Recently, it came back with some updates distributed:
- TPlinkSmartplug 0.9.18
- Octoprint 1.4

My configuration uses as well the "power off via GCODE". 

All works like a charm when I click on the icon (green or red).

Are checked:
- warning prompt
- auto connect (5)
- auto disconnect (5)

Gcode Trigger
- Gcode on delay (0)
- Gcode off delay (300) --> time for printer to cool down the nozzle.

**Comment by jneilliii** [comment]
I'm currently in development of the next release, could you try that version to see if you still have issues? Install using the url below in plugin manager. 

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.19.zip

**Comment by HuguesDug** [comment]
Hello,

Install done. It seems it works OK with 0.9.19.

I will use the new parameters that you setup power off on "idle" instead of the current GCODE controled power off. I will post how it works.
