### ISSUE TITLE
[Feature Request]: Power Off on Idle

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-TPLinkSmartplug#152]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be nice to have the option to power off on idle, similar to PSUControl plugin.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Pointer-de** [comment]
Hi, realy great. Will this feature be available in your Tasmota-Plugin too?

**Comment by jneilliii** [comment]
@Pointer-de, pretty sure it already is.

**Comment by Pointer-de** [comment]
Am i blind (yes, it could really be so! ;-) ) or is there another Version of Tasmota plugin out there than 0.8.11?
![image](https://user-images.githubusercontent.com/32867677/80498986-b424b800-896c-11ea-8986-3a5c44914b70.png)

**Comment by jneilliii** [comment]
It's worded differently. It's on the left hand side and is named `Enable Automatic Power Off..."

**Comment by Pointer-de** [comment]
I'm really blind... I allways looked for these three idle-options - sorry. Thanks
