### ISSUE TITLE
[BUG]: Octoprint Temperature graph doesn't work when plugin enabled. 

### ISSUE THREAD

**Issue by bluemanuk** [jneilliii/OctoPrint-TPLinkSmartplug#153]
**Describe the bug**
Hi, I just upgraded to Octoprint 1.4.0 and the main octprint graph does not display, it worked in safe mode so i switch off this plugin and the graph displayed as normal. 

**To Reproduce**
Installed octoprint 1.4.0 and connected printer
No graph was displayed
Ran terminal command and it worked fine
Prints also worked fine

**Expected behavior**
Graph should display as normal

**Screenshots**

![Screen Shot 2020-03-06 at 10 13 34](https://user-images.githubusercontent.com/3842693/76078477-aa00c180-5f9a-11ea-882e-8356ba113b91.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : Safari
 - OctoPrint Version 1.4.0
 - Plugin Version 0.9.18

**Additional context**

**Comment by jneilliii** [comment]
This is odd. I'm running 1.4.0 on several devices and don't have this issue. If tou look into your browser's developer console are there any errors shown on initial page load?

**Comment by bluemanuk** [comment]
Oh man, I just re-enabled it to check for browser errors and its working. Sorry dude!
