### ISSUE TITLE
[Feature Request]: Execute GCODE at power-off (or power-on?)

### ISSUE THREAD

**Issue by ahernsean** [jneilliii/OctoPrint-TPLinkSmartplug#154]
**Is your feature request related to a problem? Please describe.**
When I turn on the machine and connect OctoPrint, the print head and bed move to the center from its home position. But sometimes the print head isn't anywhere near the home. If this is the case, the bed can sometimes hit the maximum Y and try to continue, jumping the belt loudly. If the head were homed just before it powered off, this problem would disappear.

**Describe the solution you'd like**
I would like the ability to have GCODE execute when I power off the switch. This would mean that, just before disconnect, my specific GCODE would be sent. In my case, I would send G1 X0 Y0 (or something similar).

**Describe alternatives you've considered**
There may be an existing OctoPrint plugin that could send GCODE upon certain events (like "connect"), but I'm not finding anything at the moment.

**Comment by jneilliii** [comment]
Have you considered using octoprint's core gcode scripts settings? `After connection to printer is established` I assume would work for your use case.

**Comment by ahernsean** [comment]
There we go. "GCODE Scripts". I think what I want can likely be done with this functionality.
![image](https://user-images.githubusercontent.com/1649300/76320550-3a9b1280-62b7-11ea-898c-902dbf26a8bd.png)
I'll close out this issue.
