### ISSUE TITLE
[Feature Request]: Send one GCode to printer before  "Power off"

### ISSUE THREAD

**Issue by DplPl** [jneilliii/OctoPrint-TPLinkSmartplug#160]
It would be great if your Plugin would send onme GCODE to the Preinter before powering it off..

e.G. M150 to switch the LEDs off (LED strip Control Plugin)

THX!

**Comment by jneilliii** [comment]
Added with the above commit, you can test by changing the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted.

**Comment by ingo916** [comment]
I installed the release candidate and can confirm that the send gcode command works for me! thanks for adding that feature.
