### ISSUE TITLE
[BUG]: Freeze values Current Power (main page)

### ISSUE THREAD

**Issue by technoo10201** [jneilliii/OctoPrint-TPLinkSmartplug#169]
Hi ! First of all thanks for your nice work.

I would like to report a freeze "bug" in the main page of octoprint in the div TP-Link smartplug.

When i open the web page of octoprint my values like "**Current power**" & "**Total Consumption**" are not refreshed even if i put Polling Interval = 0 in the settings page...

**Video of the issue : https://www.youtube.com/watch?v=kh2RpBni-Ig**

# To Reproduce the freezed values :
1. Put Polling Interval = 0 in the settings
2. Refresh your web browser on octoprint page

![image](https://user-images.githubusercontent.com/31561379/81487622-2778d480-925f-11ea-8dfc-f733e05cbea5.png)

3. Then open the div with all info, you will see values are freezed

![image](https://user-images.githubusercontent.com/31561379/81487629-424b4900-925f-11ea-91d0-05de3487154f.png)

When i click on the refresh button, it refresh only once the value and then it is freezed again.

# **[Temporary solution] How to unfreeze the values :** 

I have to put in the settings Polling Interval = 1
Then Save settings
And go again in settings & put Polling Interval = 0
Then Save settings.

Values are not freeze anymore.
I have to do the same steps each time i refresh my octoprint page..

Any tips, bug or solution ?
Thanks in advance

**Comment by jneilliii** [comment]
Thanks, I'll update the UI to block that by setting the min to 1. And then handle on save options to filter out those as well.

![image](https://user-images.githubusercontent.com/5249455/81487936-c2a68580-9230-11ea-8d9a-77d917245bb6.png)

**Comment by jneilliii** [comment]
It's basically a 0 minute delay in an infinite loop, so setting the minimum to 1 would at least give you a minute to fix any changes necessary.

**Comment by technoo10201** [comment]
Actually, i would like to keep the "1 second" refresh to get the reel consumption at real time.
Is it possible ?

Thanks for your work.

**Comment by jneilliii** [comment]
I'm not sure I'd recommend 1 sec polling. 1 minute polling might be ok, but based on #164 1 second might be bad.

**Comment by jneilliii** [comment]
Also, to be clear. This additional polling will only effect the graphing, the final metadata added to the file for power consumption/cost is based on the `[total kWh at print complete] - [total kWh at print start]` where total kWh is being provided by the plug directly. So if you look at your Kasa app's energy tab for the plug when you start the print you will see Total Consumption, and then at the end of the print check again. Hopefully that makes sense. I still haven't received concrete evidence this is accurate in any way, as I don't know what happens for multi-day prints for example.
