### ISSUE TITLE
[BUG]: Total cost bad calculate

### ISSUE THREAD

**Issue by Cacus3** [jneilliii/OctoPrint-TPLinkSmartplug#175]
OctoPrint-TPLinkSmartplug - 0.9.20
OctoPrint 1.4.0 running on OctoPi 0.17.0

it show total cost 74.911 
![image](https://user-images.githubusercontent.com/15240495/82845364-8dfb2500-9ee4-11ea-8243-ce538cca50f6.png)

But its imposible because
![image](https://user-images.githubusercontent.com/15240495/82845409-b71bb580-9ee4-11ea-8025-0f66818812d2.png)

this is my conf
![image](https://user-images.githubusercontent.com/15240495/82845434-da466500-9ee4-11ea-8ba4-7923cf70564f.png)
 
What i have to do to this start calculating correctly?
Sorry for my English

**Comment by jneilliii** [comment]
Yeah, as mentioned in the release notes...`highly experimental, and possibly inaccurate`

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/releases/tag/0.9.19

It calculates based on the function `total consumption at print complete` - `total consumption at print start` * `cost rate`. If that `total consumption` number gets reset sometime in the middle of the print it could through off the caclculation.
