### ISSUE TITLE
[Feature Request]: Power on at start

### ISSUE THREAD

**Issue by Mearman** [jneilliii/OctoPrint-TPLinkSmartplug#176]
What the title says ^
To replace the need for manual `M80 <ip>` command

Unsure how this would interfere with printer connection. I know with printers such as the non-touchscreen Creality printers the motherboards are happy to be powered by USB and so it's possible to connect to the printer before the plug is turned on.

Might be related to #118

**Comment by jneilliii** [comment]
So your request is slightly different to #118 I guess because you want it to power printer on after octoprint startup versus on file upload/print start. I think the other would fit your needs though, so closing this one as duplicate.
