### ISSUE TITLE
[BUG]: Leading spaces in IP entry form prevent successful connections

### ISSUE THREAD

**Issue by 0xz00n** [jneilliii/OctoPrint-TPLinkSmartplug#177]
**Describe the bug**
When adding a smart plug, the IP entry form allows leading spaces, preventing the plugin from reaching the target.

**Solution**
Use something like `strip()` to remove leading/trailing spaces from that variable

**To Reproduce**
1. Add a new smart plug or modify an existing one
2. Enter a leading space before the IP address
3. Attempt to send on/off commands to the smart plug

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - OctoPrint Version: 1.4.0
 - Plugin Version: 0.9.20

**Comment by jneilliii** [comment]
How about a visual indicator in the input field if it being wrong?

**Comment by 0xz00n** [comment]
That works just as well!

**Comment by jneilliii** [comment]
I've just pushed an update to my latest dev branch that adds the error highlighting of both the input field and the row in the list. Hopefully that will help other users avoid this issue.
