### ISSUE TITLE
Plug not giving any data

### ISSUE THREAD

**Issue by Peasndcarrots** [jneilliii/OctoPrint-TPLinkSmartplug#183]
My plug isn't providing any power data. Is there a setting I need to implement to get this info to show up?

![Screen Shot 2020-06-15 at 4 01 15 PM](https://user-images.githubusercontent.com/66977640/84714074-792d1280-af21-11ea-9ba5-464c30eb13f2.png)

![Screen Shot 2020-06-15 at 3 56 30 PM](https://user-images.githubusercontent.com/66977640/84713985-2fdcc300-af21-11ea-81b7-fd160036055d.png)

**Comment by jneilliii** [comment]
What model plug do you have? Not all support power data. Typically enabling polling and restarting octoprint will get out to show the data if your model is power enabled.

**Comment by Peasndcarrots** [comment]
I have the HS100. I enabled polling and restarted, but unfortunately that didn't work.

**Comment by jneilliii** [comment]
Yep, that's the problem. That model is not a power reporting version. You'd have to have an HS110 or other device that includes "power monitoring" as a feature.
