### ISSUE TITLE
On/Off Toggle button doesn't work[BUG]: 

### ISSUE THREAD

**Issue by brianhole47201** [jneilliii/OctoPrint-TPLinkSmartplug#188]
**Describe the bug**
The on/off toggle button doesn't work.  The power icon is fine.  It's the toggle switch to turn the plugin on or off during prints that doesn't work.  Regardless of position, it will always turn the plug off after a print finishes.
**To Reproduce**
1. Put toggle in disabled position
2. perform print and it will still shutdown after print finishes

**Expected behavior**
I expect that in the disabled position, my plug will not turn off when my print finishes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: raspberry pi 4 is running octoprint.  Windows 10 is the computer I interface octoprint with
 - Browser: Chrome
 - OctoPrint Version: 1.4.0
 - Plugin Version: 0.9.23

**Additional context**

**Comment by jneilliii** [comment]
Please share a screenshot of your general settings as well as the individual plug's settings.
