### ISSUE TITLE
[BUG]: TPLinkSmartplug Plugin powers printer down immediately after start

### ISSUE THREAD

**Issue by volkastersmall** [jneilliii/OctoPrint-TPLinkSmartplug#189]
**Describe the bug**
Every time I start a printer TPLinkSmartplug Plugin immediately starts countdown and powers down my printer unless I open Octoprint interface and cancel it

**To Reproduce**
1. Power on printer
2. Wait 160 secs
3. Printer power down

**Expected behavior**
Plugin waits 15 mins (which i set in settings as Idle timeout) to power down the printer

**Screenshots**
![Capture](https://user-images.githubusercontent.com/58984241/86247301-f2309900-bbb4-11ea-9887-456849f2125d.PNG)
![Capture1](https://user-images.githubusercontent.com/58984241/86247309-f3fa5c80-bbb4-11ea-8f59-ed0fb9efc043.PNG)

**Desktop (please complete the following information):**
 - OctoPrint Version Version 1.4.0
 - Plugin Version (0.9.23)

**Comment by jneilliii** [comment]
Duplicate #171
