### ISSUE TITLE
[Feature Request]: Use browser locale for graph time

### ISSUE THREAD

**Issue by tideline3d** [jneilliii/OctoPrint-TPLinkSmartplug#196]
It'd be handy if the graph times were presented in my local timezone.  Looks like they're currently in GMT.   Its 9pm local when this screenshot was taken on the 24th.  Confusing to see the 25th on the graph.  

<img width="600" alt="image" src="https://user-images.githubusercontent.com/12903320/88445438-9b536380-cdf0-11ea-84ac-692bf7791267.png">

**Comment by jneilliii** [comment]
The record date time should be pulled from the pi's local settings, so you might want to double check those settings via `sudo raspi-config`.

**Comment by tideline3d** [comment]
That did fix my issue, but all the other Date/Time's on OctoPrint UI were just following browser locale, so I didn't think to look there.

**Comment by jneilliii** [comment]
sorry @tideline3d, the data logging has no knowledge of the browser and can be polling status even while your browser is closed. It's easy enough to configure your device for appropriate timezone/etc. I don't feel it's worth the programming effort to work around it.

**Comment by tideline3d** [comment]
Makes sense, didn't think about that the logging is done on the backend.
