### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by AirbornSRT** [jneilliii/OctoPrint-TPLinkSmartplug#198]
Can not download plugin into Octoprint. When going through plugin manager, I get the following failed comment:

ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fXYVvQ/pytuya/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fXYVvQ/pytuya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fXYVvQ/pytuya/pip-egg-info
cwd: /tmp/pip-install-fXYVvQ/pytuya/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-fXYVvQ/pytuya/setup.py", line 9, in <module>
from pytuya.const import __author__, __version__
File "pytuya/__init__.py", line 28, in <module>
import pyaes  # https://github.com/ricmoo/pyaes
ImportError: No module named pyaes
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
I believe you're looking for this issue tracker, I didn't write the tuya plugin. 

https://github.com/ziirish/OctoPrint-TuyaSmartplug/issues
