### ISSUE TITLE
unable to login to the webinterface after update

### ISSUE THREAD

**Issue by schnubbie** [jneilliii/OctoPrint-TPLinkSmartplug#20]
After the update to 1.3.5 i was not able to login to the webinterface. After i unistalled the plugin all works fine again

**Comment by jneilliii** [comment]
Try the steps in the other issue #19. Detailed steps in the post [here](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/19#issuecomment-338761763).

**Comment by jneilliii** [comment]
Closing duplicate.
