### ISSUE TITLE
[Feature Request]: Monitoring feature, HS110 no longer commercially available 

### ISSUE THREAD

**Issue by rknobbe** [jneilliii/OctoPrint-TPLinkSmartplug#203]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to buy an HS100 and it's not available :)

**Describe the solution you'd like**
Are other smartplugs with power monitoring available and supported?

**Describe alternatives you've considered**
WeMo Insight looks like it's still commercially available, is it compatible?

**Additional context**

**Comment by jneilliii** [comment]
There are other models that have energy monitoring that are supported. For example I use an HS300 power strip and it has energy monitoring. I believe the HS107 might also have it. There are reports that the KP303 works with the plugin as well.

As for Wemo, I have not integrated insights into my [wemo](https://plugins.octoprint.org/plugins/wemoswitch/) plugin for energy monitoring as of yet. The other options would be Tasmota flashable devices like the sonoff POW devices and my [Tasmota](https://plugins.octoprint.org/plugins/tasmota/) plugin, but that requires a little extra work to flash custom firmware on it.
