### ISSUE TITLE
wrong time show in graph

### ISSUE THREAD

**Issue by Janek250** [jneilliii/OctoPrint-TPLinkSmartplug#205]
device time is correct, but in the graph in octoprint is 2hours lower. I think is UTC timezone problem. My timezone is Europe/Prague UTC +2 (summer day light) and my device HS110 know it.

**Comment by jneilliii** [comment]
The timestamp in the graph/logged data is based on the local time of the device running OctoPrint. If you want that to be correct, you should fix your time settings on your device. If this is on a pi you can do that by running `sudo raspi-config` in an SSH terminal session, go to Localization options, Change Timezone.

**Comment by Janek250** [comment]
thx, my fault. change timezone works
