### ISSUE TITLE
M81 not triggering power off

### ISSUE THREAD

**Issue by hutchyx** [jneilliii/OctoPrint-TPLinkSmartplug#21]
Using OctoPrint 1.3.5 and TP-Link Smartplug 0.7.1.  
I am able to turn the TP-Link plug on and off from the icon in the octoprint nav bar but i am unable to shut off the printer using the M81 command.  I do have GCODE checkbox checked in the settings.

**Comment by jneilliii** [comment]
In the latest version you have to actually use M81 followed by the ip/hostname for the plug you add.  This was to be able to support multiple plugs.  So if your plug is ip 192.168.1.109 the command would be 

`M81 192.168.1.109`

Please let me know this works for you so I can close this issue.

**Comment by hutchyx** [comment]
Thank you... This works perfectly. 
I apologize, but I hadn't seen it documented anywhere.
Thanks for adding the multiple plug support, this is great for me!

**Comment by jneilliii** [comment]
Thanks for reporting back.
