### ISSUE TITLE
KP303 support

### ISSUE THREAD

**Issue by BigTed76** [jneilliii/OctoPrint-TPLinkSmartplug#214]
The TP Link smart power strips (3 plug KP303) don't seem to work with this plugin.  This plugin only appears to work with the single socket smart plugs.  It would be cool if power strip support with individual socket switching could be added.

**Comment by jneilliii** [comment]
They are. I use the 6 outlet model strip. You just have to pay attention to the hover text in how to enter the ip, ie 192.168.0.2/0.

**Comment by BigTed76** [comment]
Thanks for that - yep got it.  Mine has plugs labelled 1 to 3 but I have to use ip xxx.xxx.xxx.27/0 to ip xxx.xxx.xxx.27/2 I.e plug number -1.  Not a problem just thought I’d share.

This is a very good plugin and extremely useful - top marks for developing it.

Many thanks for you speedy response.
