### ISSUE TITLE
[BUG]: English Misspelling ("tempoerature") in 'Power Off on Idle' setting description

### ISSUE THREAD

**Issue by adamkld** [jneilliii/OctoPrint-TPLinkSmartplug#216]
**Describe the bug**
The word "temperature" is misspelled as "tempoerature" in the description of the 'Power Off on Idle" setting.

**To Reproduce**
Hover over the setting's checkbox.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox
 - OctoPrint Version 1.4.2
 - Plugin Version 0.9.24

**Additional context**

**Comment by jneilliii** [comment]
fixed by above commit and will be included in the next released version. Thanks for the report.
