### ISSUE TITLE
Plug Control Stopped Working on HS100 & HS110

### ISSUE THREAD

**Issue by jerryfudd** [jneilliii/OctoPrint-TPLinkSmartplug#219]
Hi,

The plugin has been working perfectly, however with no change to the system just now can't contact the plug.

I suspect that a firmware update has been applied which I was unable to prevent in the Kasa app as there is no option to ignore updates.

Anyone else in the same boat?

Model: HS100 (also have a HS110 which was also working in Octoprint with now the same Hardware/Firmware Version that is also failing.
Hardware Version: 4.1
Firmware Version: 1.1.0

I'm using a Pi4 for Octoprint 1.4.2, OctoPi 0.17.0 using version 0.9.24 of the plugin.

I tried deleting and re-adding the plug entry in the plugin, disable and re-enable plus removal and clean up of the plugin and re-install but still the same result but didn't expect it would fix it either.

**Comment by jneilliii** [comment]
duplicate #218?
