### ISSUE TITLE
[BUG]: Light not turning on automatically when print starts

### ISSUE THREAD

**Issue by timur-tabi** [jneilliii/OctoPrint-TPLinkSmartplug#228]
I'm hoping this is just simply a misunderstanding of the feature, but I want to have TPLinkSmartplug automatically turn on the LEDs over my printer whenever a print starts.  Here are my configuration pages:

![Screenshot_20201210_173714](https://user-images.githubusercontent.com/1065860/101842879-9b899c80-3b0e-11eb-8233-4412751c3a14.png)
![Screenshot_20201210_173834](https://user-images.githubusercontent.com/1065860/101842890-a17f7d80-3b0e-11eb-9c39-73d7185497f4.png)

OctoPrint 1.5.2
Python 2.7.13
OctoPi 0.15.1

**Comment by jneilliii** [comment]
Ah, I think I see the confusion. The lights will be turned on when OctoPrint starts, not a print. If you want to turn the light on when a print starts, enable the `gcode trigger` option and add `@TPLINKON 192.168.1.9` to your start gcode in your slicer or in octoprint's gcode scripts section for print start.

**Comment by timur-tabi** [comment]
That works, thanks!
