### ISSUE TITLE
[BUG]: "On with upload" greyed - not useable

### ISSUE THREAD

**Issue by epalzeolithe** [jneilliii/OctoPrint-TPLinkSmartplug#234]
**Describe the bug**
Octoprint 1.52
TP-Link smartplug 0.9.26
Cura 4.8.0
Cura Fielofview plugin

> Can't select "on with upload" in the TPlink plugin configuration- it's greyed

**To Reproduce**
So i need to manually click on octoprint TPlink icon to power up the printer, then send from Cura the print job.
Otherwise, Cura cannot connect to octoprint.

I think its due to the "On with upload" option in TPlink, but it's greyed so i cannot activate it

Thanks in advance

**Expected behavior**
When Cura send job to octoprint, it should power on the printer before with the TP link plug

**Screenshots**

**Desktop (please complete the following information):**
 - OctoPrint Version [e.g. 22]
 - Plugin Version

**Additional context**

**Comment by epalzeolithe** [comment]
In fact i shoudl see the tplink plugin in Cura like this window : 
![94508049-19602c00-01df-11eb-924a-0f19889017aa](https://user-images.githubusercontent.com/23400237/103445696-02b2f080-4c78-11eb-90b7-846704bd8970.png)

But i dont have this option !!!!

**Comment by epalzeolithe** [comment]
SOLVED 👍
i read the python code, and understand it needs a label in the tp link configuration, otherwise it doesn't find the plug.

Perhaps we could add some code to define a generic label, if no label is defined :)

        common_api_plugins = [
            ("tplinksmartplug", "TP-Link Smartplug", []), # ip
            ("orvibos20", "Orvibo S20", []), # ip
            ("wemoswitch", "Wemo Switch", []), # ip
            ("tuyasmartplug", "Tuya Smartplug", []), # label
            ("domoticz", "Domoticz", ["idx", "username", "password"]), # ip, idx, username, password
            ("tasmota", "Tasmota", ["idx"]), # ip, idx, username, password, backlog_delay
        ]  # type: List[Tuple[str, str, List[str]]]
        for (plugin_id, plugin_name, additional_data) in common_api_plugins:
            if plugin_id in plugin_data and "arrSmartplugs" in plugin_data[plugin_id]:
                for plug_data in plugin_data[plugin_id]["arrSmartplugs"]:
                    if plug_data["ip"] and plug_data["label"]:
                        plug = OrderedDict([
                            ("plugin", plugin_id),
                            ("name", ("%s (%s)" % (plug_data["label"], plugin_name))),
                            ("label", plug_data["label"]),
                            ("ip", plug_data["ip"])
                        ])
                        for key in additional_data:
                            plug[key] = plug_data.get(key, "")
                        self._available_plugs[self._createPlugId(plug)] = plug

**Comment by jneilliii** [comment]
I see you've already opened a ticket [here](https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/217) on the OctoPrint Connection plugin for cura and @fieldOfView appears to be on top of it.

**Comment by fieldOfView** [comment]
As for your original report:
> Can't select "on with upload" in the TPlink plugin configuration- it's greyed

You have to enable the `Upload Event Monitoring` option in the TP-Link Smartplug Settings in OctoPrint for that option to be enabled.

**Comment by jneilliii** [comment]
Oh right, oops. forgot to mention that. Thanks Aldo.
