### ISSUE TITLE
[BUG]: Cannot see/access the TP Link graph tab

### ISSUE THREAD

**Issue by stantond** [jneilliii/OctoPrint-TPLinkSmartplug#236]
I cannot see the tab that is meant to be added by this plugin on the Octoprint home screen.

Is this tab supposed to show immediately, or are there some prerequisite steps before it's available?

I'm also using TabOrder - the plugin tab is visible in the TabOrder settings, and I've set it to be visible.

I _do_ see a TP-Link Smartplug box in the left hand side bar with refresh and auto power on buttons, and I'm able to use the shortcuts in the header bar to turn on/off my smart plug.

**Comment by jneilliii** [comment]
The tab will only be visible if you are using power monitoring devices, and only after a few cycles, or status checks have completed with the polling option enabled.
