### ISSUE TITLE
[BUG]: No reaction when I click to switch on/off my HS100

### ISSUE THREAD

**Issue by Fleoxi** [jneilliii/OctoPrint-TPLinkSmartplug#237]
**Describe the bug**
After configuration, registration of my connected TP Link HS100 socket, no reaction even after Pi restart when I want to switch on/off my socket (and thus my 3D printer)

**To Reproduce**
1. Go to Octoprint
2. Click on the Bolt Icon
3. See error

**Expected behavior**
I expect the plug to work

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] IOS/Windows
 - Browser [e.g. chrome, safari] : Safari/Opera
 - OctoPrint Version [e.g. 22] : Latest
 - Plugin Version : Latest

**Additional context**
/

**Comment by jneilliii** [comment]
Please enable debug logging in the plugin's settings, restart OctoPrint and try again. Once that has failed, please go into OctoPrint's settings and download the file plugin_tplinksmartplug_debug.log and share it here by dragging it into a comment.
