### ISSUE TITLE
[BUG]: The plug does not turn off at the end of a print job.

### ISSUE THREAD

**Issue by Fleoxi** [jneilliii/OctoPrint-TPLinkSmartplug#238]
**Describe the bug**
The plug does not turn off at the end of a print job, can't be more explicit.

**To Reproduce**
1. Start Print
2. Wait till' the end

**Expected behavior**
I expect the plug to turn off.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : IOS & Windows
 - Browser [e.g. chrome, safari] : Opera
 - OctoPrint Version [e.g. 22] : Latest
 - Plugin Version : Latest

**Additional context**
-

**Comment by Fleoxi** [comment]
Additional precision: Manually via the button in the navbar, everything works perfectly.

**Comment by jneilliii** [comment]
Please share screenshots of your settings. To automatically power off you have to enable either gcode commands and put that in your end gcode or idle timeout options.

**Comment by Fleoxi** [comment]
![Capture d’écran du 2021-01-12 22-00-41](https://user-images.githubusercontent.com/43684766/104374171-c4dc8480-5521-11eb-8da5-a9f811d251dc.png)
![Capture d’écran du 2021-01-12 22-01-05](https://user-images.githubusercontent.com/43684766/104374172-c5751b00-5521-11eb-95cd-fa63c2841f74.png)
![Capture d’écran du 2021-01-12 22-01-36](https://user-images.githubusercontent.com/43684766/104374174-c60db180-5521-11eb-8413-afdb750c9c77.png)

**Comment by jneilliii** [comment]
Ok, thanks. I believe what issue you might be running into is related to the printer's command buffer. If you increase your gcode off delay to something a little higher to give the print time to actually complete before the off command is triggered I think it will work as expected. Start with something like 10 or 15 and increase a little at a time. It's really going to depend on how big the firmware's buffer is as to how long that delay needs to be.

**Comment by Fleoxi** [comment]
How to set a delay as you advise in this case? I am not very used to the GCode

**Comment by jneilliii** [comment]
I was referring to the plugin's settings here.

![image](https://user-images.githubusercontent.com/5249455/104379555-9cd82b80-54f7-11eb-9472-e4529b0b4d52.png)

**Comment by Fleoxi** [comment]
Okay perfect, I'll try this
