### ISSUE TITLE
[BUG]: Plug turns on, Octoprint wants to connect, plug shuts down.

### ISSUE THREAD

**Issue by OxygenGS** [jneilliii/OctoPrint-TPLinkSmartplug#240]
Hello,

I did gte a Tp link HS100 today. Did install the plugin and it responds.. jeej.
However.. Once i click the icon on the top to turn the plug on, all is fine. 
BUT as soon as octorpint wants to connect to the printer, the plug turns off...
Someone who can help me out :(?

**Comment by jneilliii** [comment]
Please share your settings. There are some known conflicts with some printers that are USB back powered and disconnect monitoring enabled.

**Comment by OxygenGS** [comment]
Nvm.. i feel so stupid! i didnt had the USB cable connected...
Because i changed the PSU before i installed the plugin haha.. sorry!

**Comment by OxygenGS** [comment]
But i still have 1 question: how can i shut down my pi also once the printer goes off ?

**Comment by jneilliii** [comment]
Something like this should work. Just make sure the timer is longer than it takes for your pi to shutdown completely, 30 seconds is probably fine I would think, but you might want to time it manually first just to be sure.

![image](https://user-images.githubusercontent.com/5249455/105616217-57431a80-5da3-11eb-98e1-d9aeacb98c45.png)

**Comment by OxygenGS** [comment]
Thnx!!!
