### ISSUE TITLE
[Feature Request]: HS300 Support

### ISSUE THREAD

**Issue by ingo916** [jneilliii/OctoPrint-TPLinkSmartplug#242]
I have a TP-Link HS300 power strip. Would like to know if you can or will support this device. https://www.amazon.com/gp/product/B07G95FFN3/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

It’s a power strip with 6 smart outlets. It’s easier to use this rather than the individual single smart outlets, saves room.

**Comment by jneilliii** [comment]
That's the exact device I use personally, you just have to add the 0 based index of the plug on the strip to the ip address...

![image](https://user-images.githubusercontent.com/5249455/105663010-19c3b780-5e9f-11eb-9d60-17970ae28804.png)

**Comment by ingo916** [comment]
Thanks!!
