### ISSUE TITLE
[BUG]: plug numbers do not match

### ISSUE THREAD

**Issue by ingo916** [jneilliii/OctoPrint-TPLinkSmartplug#243]
**Describe the bug**
In the TP-Link Kasa app, the outlets on my HS300 are listed as 1-6 as shown in the following screenshot. 
However in the plugin it's off, 1 would be outlet 2 on the power strip then 2 would be outlet 3 and so on. 
**Screenshots**
![FD47C4C1-4503-46C6-A7C6-EDBE83D798BE](https://user-images.githubusercontent.com/41309095/105670536-0cee9600-5e96-11eb-8f71-72d89d733e38.jpeg)

 - OctoPrint Version 1.5.3
 - Plugin Version 0.9.26
- TP-Link Firmware 1.0.19

**Comment by jneilliii** [comment]
The instructions for multiple plug/strip devices is to use a 0 based number, so for now you should be able to subtract 1 from the number listed in the plugin's settings.

**Comment by jneilliii** [comment]
adjusted code in above commit to match the index to the labels shown on the device and in the app, you can switch the release channel to `Release Candidate` in OctoPrint's software update settings and upgrade when prompted to try it out. @tideline3d may be interested in this one as well 😄
