### ISSUE TITLE
[BUG]: Turning the plug on after idle shutdown causes the printer to re-start last job

### ISSUE THREAD

**Issue by samwiseg0** [jneilliii/OctoPrint-TPLinkSmartplug#244]
**Describe the bug**
Turning the plug on from the UI/manually causes the printer to start printing the last job it had before it was powered off. 

**To Reproduce**
1. Have the plugin shutdown the printer after idle for x time
2. Turn the plug on manually/from the UI
3. The printer will start printing the last job instead of sitting idle.

**Expected behavior**
When the printer is turned back on it should remain in an idle state. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - OctoPrint Version 1.5.3
 - Plugin Version 0.9.26

**Additional context**
N/A

**Comment by jneilliii** [comment]
Thanks @samwiseg0, I know what I need to do to fix this, it's definitely a bug since I'm not clearing out the flag for autostart on print completion/cancel.

**Comment by jneilliii** [comment]
This should be resolved by the above commit.
