### ISSUE TITLE
[BUG]: not a bug! Works with firmware 1.1.3 on HS100

### ISSUE THREAD

**Issue by dretful** [jneilliii/OctoPrint-TPLinkSmartplug#245]
You mention in your docs that the new firmware stops these working in some cases. I have the UK HS100 v1.0 with 1.1.3 firmware it shipped with. It works fine with your excellent software!

I had a real problem getting the smart plug address as it seems somehow it’s hidden in my virginmedia router. I used the “multiping” app to look for devices then plugged the smart plug in and looked again to see which new ip it was. It looked like 100% packet loss, but sure enough when I entered that IP into your addin config it worked. 

Only posting this in case it helps someone.

**Comment by jneilliii** [comment]
Interesting find @dretful that's even more of a reason to try and get #76 feature request implemented I suppose.
