### ISSUE TITLE
Excited!!! Works with firmware 1.5.2 !!

### ISSUE THREAD

**Issue by sep2345** [jneilliii/OctoPrint-TPLinkSmartplug#246]
I just ordered and received a new TP-Link HS100 and discovered that it came with firmware 1.5.2 installed. Upon attaching it to my network it wanted to update to the latest firmware version. I cancelled that request of course and stayed at 1.5.2.

I can report that your awesome plugin WORKS with version 1.5.2 !!! It was my understanding that things were broken at 1.1.1?

Anyways, I hope this info helps others!
Thanks,
Scott

**Comment by jneilliii** [comment]
Thanks for the info. There have been reports of specific version of UK firmware to be broken, but a way to get it working again. Thanks for your report.
