### ISSUE TITLE
[Feature Request]: Power consumption monitoring

### ISSUE THREAD

**Issue by dualznz** [jneilliii/OctoPrint-TPLinkSmartplug#253]
**Additional context**
Would like the ability to see realtime power consumption on KASA HS100, the unit works with this plugin with no issue but haveing the ability to see power consumption over time would be quite nice.

**Comment by jneilliii** [comment]
The plugin can do that with a a plug that supports power monitoring, like the HS110 or the HS300. The HS100 doesn't have that information available.
