### ISSUE TITLE
Current time is not displayed correctly.

### ISSUE THREAD

**Issue by Gozania** [jneilliii/OctoPrint-TPLinkSmartplug#271]
Love the plugin, however the times in the graph are not correct.  I would like to see the times coincide with the actual time.  It seems it is 16 hours behind my actual time....  Currently 20:00 but graph is only showing a current time of 04:00...  Is there any way to remedy this issue?  Love being able to monitor my power usage and costs.

![Screenshot 2021-05-11 200556](https://user-images.githubusercontent.com/83924000/117912488-7d2df580-b294-11eb-8e17-367d9ed4efbe.png)

**Comment by jneilliii** [comment]
It's based on the time configured on the pi. In order to fix that you need to SSH to the pi and adjust the timezone and time settings using `sudo raspi-config`.
