### ISSUE TITLE
[Feature Request]: Add temperature sensor input

### ISSUE THREAD

**Issue by StudioRATATA** [jneilliii/OctoPrint-TPLinkSmartplug#278]
**Is your feature request related to a problem? Please describe.**
I would be nice to have extra temperature sensor inputs. Beside the two existing of the bed and extruder.
I've added a DS18B20 sensor the monitor the enclosure temperature. I would be nice to shut off the printer when it exceeds a certain temperature. Also it would be useful to use in combination with a enclosure heater. 

**Describe the solution you'd like**
I would like an option to add an extra temperature sensor. On which the plugs can be switched.

**Comment by jneilliii** [comment]
Although this would be a nice feature to have, because of it's dependency on GPIO I'd rather not implement it. You should look into the enclosure plugin for your needs though, it does support temperature sensors if I'm not mistaken.
