### ISSUE TITLE
KP303

### ISSUE THREAD

**Issue by staticgroup** [jneilliii/OctoPrint-TPLinkSmartplug#280]
Hey Jneilliii,
is there a way to specify the plug on a kp303 to get that to work as I have multiple smart plugs setup around the printer so would simplify my setup

**Comment by jneilliii** [comment]
Yes, you should be able to use /<plug #> after the ip address to address each individual plug. I do this with the 6 outlet strip personally. 

![image](https://user-images.githubusercontent.com/5249455/129468698-8a26bada-026b-4dd0-9b97-95c4a7796b62.png)
