### ISSUE TITLE
[Feature Request]: Remove all telemetry data / reset

### ISSUE THREAD

**Issue by GrimWreeper** [jneilliii/OctoPrint-TPLinkSmartplug#283]
Firstly, love the plugin, been using it since I got my ender,

A way to clear all the plugs previous telemetry history and start again, without having to remove & replace plug. 
{It's fully possible that this exists and I've just missed it :D }

**Comment by jneilliii** [comment]
It is possible to do, but not from the UI. You would have to delete the 'energy_data.db' file in `/home/pi/.octoprint/data/tplinksmartplug`

**Comment by GrimWreeper** [comment]
Np problem, If I shut down octoprint. delete the db, will I recreate itself?

**Comment by jneilliii** [comment]
Yes, it will when OctoPrint initializes.
