### ISSUE TITLE
I noticed there is a warning that kasa tp-link devices stopped working

### ISSUE THREAD

**Issue by cybernard** [jneilliii/OctoPrint-TPLinkSmartplug#289]
https://github.com/p-doyle/Python-KasaSmartPowerStrip

You might want to try this git hub project because it still works with all my kasa devices.

**Comment by jneilliii** [comment]
Thanks for the heads up, but to date it only seemed to be one specific batch of UK devices and I believe has since been reverted. The plugin still works on all devices I've tested, including the power strips.
