### ISSUE TITLE
Turn off when print complete

### ISSUE THREAD

**Issue by fromagek** [jneilliii/OctoPrint-TPLinkSmartplug#29]
A nice feature would be to turn off the printer, when the print is complete.
Best florian

**Comment by jneilliii** [comment]
You can achieve this by enabling GCODE processing and in your slicer's end gcode set-up or in OctoPrint's settings > GCODE Scripts.  Follow the format detailed on the [readme](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug#settings-explained) page. Make sure to disable any of the warning options for this as it will interfere with the process.

**Comment by fromagek** [comment]
THX haden't seen it.
