### ISSUE TITLE
[BUG]: MP Mini Select V2 never seen as idle

### ISSUE THREAD

**Issue by DerArtz** [jneilliii/OctoPrint-TPLinkSmartplug#294]
Description
I love this integration but it never figures out that my MP mini select is idle. Under the gcode commands to ignore all I have is M105.  I think the problem is my M105 command is actually something closer to M105*39.  The other problem is this number changes constantly.

**To Reproduce**
Leave the printer running with nothing happening other than temperature updates.

**Expected behavior**
After the 30 minutes of idle time the integration would turn off the printer.

**Screenshots**
![image](https://user-images.githubusercontent.com/10697797/150903459-d01fbc88-b077-44b4-8825-9a9eba10d13e.png)
![image](https://user-images.githubusercontent.com/10697797/150903504-ccb565ab-9300-43a5-aa36-70f8eab7bd07.png)

 - OS: Octopi
 - Browser Firefox
 - OctoPrint Version 1.7.3
 - Plugin Version 1.0.1

**Comment by jneilliii** [comment]
That number at the end is a checksum, doesn't effect the actual command to ignore. In the device's detailed settings, did you enable off on idle there too?
