### ISSUE TITLE
[Feature Request]: Update list of supported devices

### ISSUE THREAD

**Issue by b-morgan** [jneilliii/OctoPrint-TPLinkSmartplug#298]
**Is your feature request related to a problem? Please describe.**
I am using:

1. HS105 hardware version 1.0, firmware version 1.5.6 successfully.
2. HS103 hardware version 3.0, firmware version 1.0.3 successfully.
3. HS103 hardware version 5.0, firmware version 1.0.3 successfully.

**Describe the solution you'd like**
I believe you can add HS105 and HS103 to your list of supported TP-Link devices

**Comment by jneilliii** [comment]
Thanks @b-morgan added into the rc branch and will go live once I merge those changes in.
