### ISSUE TITLE
Documentation Update - KP303

### ISSUE THREAD

**Issue by Ragnar123456** [jneilliii/OctoPrint-TPLinkSmartplug#303]
I can confirm that the Kasa KP303 works with this plugin.  Each of the three plugs can be individually controlled as per the documentation of <ip>/#.

**Comment by jneilliii** [comment]
added in https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/pull/304/commits/cdae1ef16b8e7332458676677afe570e599503f0 will update on the readme once merged.

**Comment by jneilliii** [comment]
Thanks for reporting compatibility.
