### ISSUE TITLE
Impossible to connect my TP-link TapoP100 [BUG]: 

### ISSUE THREAD

**Issue by Deadpoule** [jneilliii/OctoPrint-TPLinkSmartplug#308]
Hi,
I try everything i can but your plugin doesn't work with my tp-link Tapo P100. 
The power icon remain grey, never green whatever i try. 

I saw  a post where you already respond about this issue, but the solutions proposed (install some forks of your plugin) doesn't work at all.
I'd try every forks but it still the same. 

Is there any chance that you found a solution to fix this? 

Thank you for your work :)

Octoprint 1.7.3
Tapo 2.4.70
Win 10
My octoprint log report this issue:
2022-05-08 19:32:21,249 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin taposmartplug

**Comment by jneilliii** [comment]
It states very clearly that this plugin works with Kasa devices, not Tapo. There is a fork of this plugin that is not registered on the plugin repo for you device. https://github.com/Tyfy/OctoPrint-TapoSmartplug

I think there's also a PSU Control sub-plugin that works with Tapo devices as well. https://plugins.octoprint.org/plugins/psucontrol_tapo/

**Comment by Deadpoule** [comment]
Thank you for your reply, i will try it.

**Comment by jneilliii** [comment]
Version 2.0.0rc1 is out and is working with my Kasa based HS300, Kasa based HS103 and Tapo based P115. You can change the release channel in OctoPrint's Software Update settings to Release Candidate and update when prompted to get this version. 

Things I've noted so far, the P115 doesn't provide as much energy data as the kasa devices do. Tapo devices will require entering your username and password registered in the Tapo app, Kasa devices don't require those settings to be entered.
