### ISSUE TITLE
[Feature Request]: Ability to "lock" printer on (or off), overriding conditions and timeouts

### ISSUE THREAD

**Issue by puterboy** [jneilliii/OctoPrint-TPLinkSmartplug#315]
I typically use a 30-60min idle timeout but sometimes I would like to keep the printer on longer even when idle -- especially when I am testing something.... and it can be easy to miss the warning popups on the screen.

I could manually change the settings each time, but it would be nice if there were an override to keep the printer on (or off) regardless of other conditions (except perhaps thermal runaway). 

Perhaps a long press on the button could be used to trigger an override with the icon changing to show a green (or red) lock instead of the thunderbolt to indicate the locked state.

**Comment by jneilliii** [comment]
There's a toggle switch in the sidebar to disable idle timeout.

**Comment by puterboy** [comment]
Hmmm... Which sidebar?
I just see an on/off button in my navbar and then the detailed configs under settings.

**Comment by jneilliii** [comment]
It looks different for me because I have UI Customizer and have it moved to the top, but it looks like this...

![image](https://user-images.githubusercontent.com/5249455/183328394-bd52544e-dde8-446d-9416-e26acb6592c5.png)

**Comment by puterboy** [comment]
I only see the thunderbolt icon in my nav bar
![image](https://user-images.githubusercontent.com/1993858/183333393-3b9e564d-d649-4ac0-b426-a2f3751ed7a8.png)

I don't get anything in any of the tabs.

**Comment by puterboy** [comment]
Never mind - I see it below the fold on the right nav. I just had never scrolled that low :)
