### ISSUE TITLE
Working with UK plug KP105

### ISSUE THREAD

**Issue by hamid-elaosta** [jneilliii/OctoPrint-TPLinkSmartplug#317]
I saw mention that the KP115 in the UK was working but no mention of the KP105 which is currently on sale on Amazon for ~£11.

I bought one and can confirm that it works with this plugin for switching on/off.

Note this "mini" plug does not appear to have energy monitoring, it's simply a switch.

I configured it using the "offline" mode in the Kasa app (respect to TPLink for not forcing you to register to use it), found the IP by scanning from my Android phone with fing and typed it into the plugin config and it just worked.

EDIT: Firmware version is 1.0.0

**Comment by jneilliii** [comment]
Thanks for the report. Added with the above commit to the readme.
