### ISSUE TITLE
TPlink plugin and  Chrome

### ISSUE THREAD

**Issue by glenncol** [jneilliii/OctoPrint-TPLinkSmartplug#318]
Hi all, 

I have installed  Octoprint along with the TPlink smart plug plugin and have noticed an issue with Google Chrome, The little power icon will not  populate on the top of Octoprint and when trying to add a plug to the plugin, Octoprint freezes every time, but if I try the same operation via Firefox there Iss no issue

**Comment by jneilliii** [comment]
I use chrome with the plugin. Can you share what shows in your browser's developer tools, console tab during initial page load?
