### ISSUE TITLE
[BUG]: README says incorrect indexing

### ISSUE THREAD

**Issue by DaveNugent** [jneilliii/OctoPrint-TPLinkSmartplug#327]
**Describe the bug**
The README says

> IP or hostname of plug to control. For strip devices use the format <ip>/<0 based socket index>, ie 192.168.0.2/0 would control the first socket in the strip.

but for my KP303 it needed to be 1 indexed, which matches the labeling in the Kasa app

**To Reproduce**
Try controlling a KP303 socket that is using the most recent firmware as of 1/9/2023

**Expected behavior**
The socket controlled will be based on 1 indexing

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - OctoPrint Version 1.8.6
 - Plugin Version 1.0.2

**Comment by jneilliii** [comment]
Oh yeah, I had changed that to make it easier for users, just forgot to update the readme. Thanks.

**Comment by jneilliii** [comment]
updated in the rc branch and will be updated on next stable release.
