### ISSUE TITLE
With KP303 and lamp on port 2 kills connection to printer 

### ISSUE THREAD

**Issue by Grayzone233** [jneilliii/OctoPrint-TPLinkSmartplug#332]
Using KP303 switch lamp on port 2 Optoprint on port 1. If you have a connection from Octoprint to the printer and turn off the Lamp, Octoprint will disconnect from the printer.  This is with the latest 1.0.3 version, the earlier version worked fine. Not a good thing when you are printing some thing as it kills it.

**To Reproduce**
1. web interface Octoprint, connect to printer and have lamp on.
2.3. Click on the lamp power button to turn of lamp.
4. Printer is now disconnected,

**Expected behavior**
Expect the printer to stay connected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 -  - Browser Google Chrome
 -  - OctoPrint Version 1.8.7
 - Plugin Version 1.0.3

**Comment by jneilliii** [comment]
Please enable debug logging in the plugins settings, restart OctoPrint and reproduce the issue. Then share the plugin_tplinksmartpkug_debug.log file from OctoPrint's logging section in settings and screenshots of all your settings for the plugin.

**Comment by Grayzone233** [comment]
Here you go.
![smart2](https://user-images.githubusercontent.com/57326375/227738188-e3a121a7-1ccd-410a-b9d6-de4a3edc204c.GIF)
![smart1](https://user-images.githubusercontent.com/57326375/227738191-66f53ee2-f5fa-42f6-aed2-2d0fffc3464a.GIF)
[octoprint.zip](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/11069931/octoprint.zip)

**Comment by jneilliii** [comment]
Please provide the individual plug settings as well and that zip doesn't seem to contain the `plugin_tplinksmartpkug_debug.log` file requested, just octoprint.log (which has loads of smartfilamentsensor plugin errors BTW).

**Comment by Grayzone233** [comment]
Ok, last time it did not create a tplin...log file. Here are the two plug settings (everything below the cut off is off.
Trying to get log file now.
[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/11070343/plugin_tplinksmartplug_debug.log)

![port2](https://user-images.githubusercontent.com/57326375/227745389-68210d57-5d4f-4c0c-bc30-e655ebfcbebb.GIF)
![port1](https://user-images.githubusercontent.com/57326375/227745390-97c57e80-49fa-4240-bb21-b5e9605dec4d.GIF)

**Comment by jneilliii** [comment]
Disable the Auto Disconnect and Auto Connect options on the Lamp settings. You could also probably disable the warning prompt and warn while printing for that one as well.

**Comment by Grayzone233** [comment]
Thanks that fixed it!!!
