### ISSUE TITLE
make plugin compatible for mainsail (moon raker)

### ISSUE THREAD

**Issue by luco85** [jneilliii/OctoPrint-TPLinkSmartplug#357]
Hi, your plugin is one of the best for 3d printing. Recently I moved to mainsail and is not possible use the feature of time delay after shutdown rasp (there is a delay but is not a countdown like your). I can do this by code from terminal, and run a script before shutdown raspy but with this I have a problem and not work. So I ask if you never think to integrate this plugin to mainsail. Thanks for your work and time

**Comment by jneilliii** [comment]
sorry, don't use those platforms, so recommend requesting that ability on whatever plugin is available already on the mainsail side.

**Comment by luco85** [comment]
Ok thanks
