### ISSUE TITLE
Wrong plugin name in power-off prompt

### ISSUE THREAD

**Issue by benlye** [jneilliii/OctoPrint-TPLinkSmartplug#43]
![capture](https://user-images.githubusercontent.com/23322579/35556478-3f4b104a-059a-11e8-996f-a01bdf8542e9.PNG)

I think you may have left this in there by accident...
https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/blob/69fbbac2c37df58f4b72328f0b15b8313b98bb8a/octoprint_tplinksmartplug/templates/tplinksmartplug_navbar.jinja2#L8

Also, it would be cool if the prompt showed the label rather than the IP address.

Great plugin, by the way!

**Comment by jneilliii** [comment]
Thanks for pointing that out.  Fixed with 0.9.1.
