### ISSUE TITLE
Version 0.9.2 does not display "bolt" using IE11

### ISSUE THREAD

**Issue by mikeap** [jneilliii/OctoPrint-TPLinkSmartplug#44]
Updated to 0.9.2 and the bolt is not displayed when using IE11

**Comment by jneilliii** [comment]
Confirmed bug. Will work on getting this resolved. Not sure what the difference is between IE and Chrome, but don't have that problem there.

**Comment by jneilliii** [comment]
Fixed with release 0.9.3.

**Comment by mikeap** [comment]
thanks
