### ISSUE TITLE
Some Icons won't show up

### ISSUE THREAD

**Issue by CaptCode** [jneilliii/OctoPrint-TPLinkSmartplug#56]
Hey,

really cool  and simple Plugin - thank you for that!

just a minor issue, I noticed that some icons from the cheatsheet can not be used because they will not be displayed.
For example the icon "plug" with unicode "f1e6"
![plug](https://user-images.githubusercontent.com/4345030/43971803-bed413b4-9cd2-11e8-9ccd-a860aa83b690.png)

It is displayed like this when the cursor hovers over it:
![hover](https://user-images.githubusercontent.com/4345030/43971882-fa046e20-9cd2-11e8-8dd5-21625b7cdd21.png)

**Comment by jneilliii** [comment]
Yeah, unfortunately, the links got messed up and are redirecting to the most current fontawesome library.  The only supported icons at this time are the ones at this link.

https://fontawesome.com/v3.2.1/icons/
