### ISSUE TITLE
Support for broadlink sp3

### ISSUE THREAD

**Issue by vstoms** [jneilliii/OctoPrint-TPLinkSmartplug#58]
Hey,

Do you have any plans to also support Broadlink (http://www.ibroadlink.com/sp3/)?

**Comment by jneilliii** [comment]
Don't really know anything about that device. Do you know if it is controllable via mqtt protocol or web based api?

**Comment by vstoms** [comment]
I think this is the libary you can use: https://github.com/mjg59/python-broadlink

**Comment by jneilliii** [comment]
Sorry, I don't have a desire to pursue this fork.
