### ISSUE TITLE
Keep loosing connection to plug. 

### ISSUE THREAD

**Issue by LazaroFilm** [jneilliii/OctoPrint-TPLinkSmartplug#63]
I keep getting this error. The plug is on a fixed ip. 
```
TP-Link Smartplug Error
Status unknown for 192.168.1.246. Double check IP Address\Hostname in TPLinkSmartplug Settings.
```

**Comment by jneilliii** [comment]
Please enable debug logging, attempt to toggle the device and then upload your plugin_tplinksmartplug_debug.log file here. One issue in the past where this was happening was related to the user's network.  His OctoPrint server was on a different network than his plug and it could connect to it to control.  Some kind of network routing issue. Also, what model plug do you have and what version of firmware?
