### ISSUE TITLE
TP Link Lightbulb (LB100, LB110, LB120, LB130) support?

### ISSUE THREAD

**Issue by bmcgough** [jneilliii/OctoPrint-TPLinkSmartplug#64]
The plugin is working well for me and is nicely built!

I'd love to be able to control a TP Link Smart lightbulb from Octoprint, to illuminate my printer better for the webcam.

It looks like the protocol is similar, if not the same. I found this: https://github.com/briandorey/tp-link-LB130-Smart-Wi-Fi-Bulb 

I have an LB110 and would be happy to test it.

Thanks!

**Comment by jneilliii** [comment]
I already have one up for testing. See over here. Was waiting in feedback. 

https://github.com/jneilliii/OctoPrint-TPLinkSmartBulb
