### ISSUE TITLE
Loses plug's IP after update

### ISSUE THREAD

**Issue by LazaroFilm** [jneilliii/OctoPrint-TPLinkSmartplug#67]
Everytime the plugin is updated I loose the plug's IP. Is there a way to have that backed up during updates? It's a pain to have to reconfigure the whole thing every time. 
PS: the plug seems much more responsive now after the update thanks!

**Comment by jneilliii** [comment]
That's odd.  The previous settings should only be wiped out if I make a change to the "settings version" in the plugin and I didn't do that for this update.  Let me do some testing and I'll get back with you.  It may be similar to another issue that I heard of from someone else on another plugin that if the settings are saved prior to getting loaded completely the settings are defaulted to their default state, which is single plug with no ip.

**Comment by jneilliii** [comment]
I take that back.  I've been developing this version for so long I forgot that there was a "settings version" update in this latest release.  The only reason I do that is when there is a change to the configuration of the individual plug options.  For the next release where that is necessary I'll change the logic to not default the settings but to loop through the plugs configured and add any necessary options from defaults.

**Comment by jneilliii** [comment]
I just pushed a new update that in theory shouldn't wipe out all the previously configured plugs.  Please verify that is the case for you.
