### ISSUE TITLE
M81 plus IP not recognized after the update. 

### ISSUE THREAD

**Issue by LazaroFilm** [jneilliii/OctoPrint-TPLinkSmartplug#69]
Hi, 
I'm trying to issue a M81 with the ip after it and Klipper returns 
`Recv: // Unknown command:"M81 192.168.1.XXX"` (removed the last 3 digits of the IP)
The printer stays on. the plug works when I press the button in Octoprint's task bar, but not with the M81 IP command. This used to work before the last update.

**Comment by jneilliii** [comment]
Are there any errors in octoprint.log?
