### ISSUE TITLE
M80 command stops print

### ISSUE THREAD

**Issue by chipdice** [jneilliii/OctoPrint-TPLinkSmartplug#77]
I've got the plugin to turn on my tp link smartplug by putting in the M80 command with the correct IP, however this causes my printout to immediately get cancelled. I'm using the original Prusa i3 MK3 printer. How do I avoid it cancelling the printout?

**Comment by jneilliii** [comment]
Can you please share a screenshot of the plug's settings?  I think the issue might be related to the Auto Connect option maybe?  If not then you may want to attempt using the custom action command `@TPLINKON` instead of M80.

**Comment by chipdice** [comment]
<img width="418" alt="2018_11_29_21_42_38_octoprint" src="https://user-images.githubusercontent.com/777986/49265622-e309c800-f420-11e8-9290-2af87aa206b4.png">

**Comment by chipdice** [comment]
Should I try with autoconnect off to see?

**Comment by jneilliii** [comment]
Yeah, I'd try turning off the option to auto connect.

**Comment by chipdice** [comment]
ok, will do and let you know. Thanks

**Comment by chipdice** [comment]
Turning Autoconnect off worked. Thanks
