### ISSUE TITLE
TP-Link Smart Strip

### ISSUE THREAD

**Issue by romainrobotics** [jneilliii/OctoPrint-TPLinkSmartplug#81]
Does this plugin work with the Kasa Smart Strip? I have multiple printers that I'd like to power individually with it. If not, would it be easy for someone familiar with the project to implement something like this related repo?

https://github.com/p-doyle/Python-KasaSmartPowerStrip

I'm willing to spend some time to try to make it work but I'm pretty new at this and very unfamiliar with how to create plugins.

**Comment by jneilliii** [comment]
In theory it would some it's using the same decrypt/encrypt functions. Wouldn't be too difficult to make adjustments to a fork of this plugin I'd it doesn't work exactly.

**Comment by romainrobotics** [comment]
The smart strip uses the same IP address for the entire device. I'll look around in the code to see if I can find anything on how I could modify it to take IP address and plug number when using a smart strip.

**Comment by romainrobotics** [comment]
From line 113 in the source of that other repo KasaSmartPowerStrip.py, it looks like this pair is added to the JSON similar to line 108 of OctoPrint-TPLinkSmartplug/octoprint_tplinksmartplug/__init__.py

"context":{"child_ids":["' + plug_id + '"]},

The plug_id is found with their function at line 172 in KasaSmartPowerStrip.py

It also appears to be able to toggle them as groups, but I'm not sure how necessary that would be for Octoprint unless you want to be able to turn off all printers together.

**Comment by jneilliii** [comment]
Ok, I've looked into that code a little bit.  If you don't mind I was wondering if you could install this plugin, and in settings enable debug logging and set your ip address of your strip then attempt to click the power.  This should log the return commands sent to see if it will be difficult to integrate or not. I need the plugin_tplinksmartplug_debug.log file after you attempt to press the button.

**Comment by romainrobotics** [comment]
I accidentally locked myself out of my house this morning so I'll try to
get this tested tonight, otherwise tomorrow.

Thank you for looking into it

**Comment by romainrobotics** [comment]
Here's the output of the log file

`[2019-01-12 23:03:47,094] DEBUG: Checking status of 192.168.0.108.
[2019-01-12 23:03:47,095] DEBUG: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
[2019-01-12 23:03:47,096] DEBUG: IP 192.168.0.108 is valid.
[2019-01-12 23:03:57,107] DEBUG: Could not connect to 192.168.0.108.
[2019-01-12 23:03:57,108] DEBUG: {'emeter': {'err_code': True}, 'system': {'get_sysinfo': {'relay_state': 3}}}
[2019-01-12 23:04:45,314] DEBUG: Checking status of 192.168.0.102.
[2019-01-12 23:04:45,317] DEBUG: {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}}
[2019-01-12 23:04:45,317] DEBUG: IP 192.168.0.102 is valid.
[2019-01-12 23:04:45,644] DEBUG: Sending command {"system":{"get_sysinfo":{}},"emeter":{"get_realtime":{}}} to 192.168.0.102
[2019-01-12 23:04:45,647] DEBUG: « ÿ+"system":{"get_sysinfo":{"sw_ver":"1.0.6 Build 180627 Rel.081000","hw_ver":"1.0","model":"HS300(US)","deviceId":"80060636AE5C93BC23D207495709446E1A9D36D8","oemId":"5C9E6254BEBAED63B2B6102966D24C17","hwId":"34C41AA028022D0CCEA5E678E8547C54","rssi":-55,"longitude_i":-832196,"latitude_i":422817,"alias":"TP-LINK_Power Strip_2E46","mic_type":"IOT.SMARTPLUGSWITCH","feature":"TIM:ENE","mac":"0C:80:63:E2:2E:46","updating":0,"led_off":0,"children":[{"id":"80060636AE5C93BC23D207495709446E1A9D36D800","state":0,"alias":"light","on_time":0,"next_action":{"type":-1}},{"id":"80060636AE5C93BC23D207495709446E1A9D36D801","state":0,"alias":"MPSM-1","on_time":0,"next_action":{"type":-1}},{"id":"80060636AE5C93BC23D207495709446E1A9D36D802","state":0,"alias":"MPSM-2","on_time":0,"next_action":{"type":-1}},{"id":"80060636AE5C93BC23D207495709446E1A9D36D803","state":0,"alias":"Wanhao i3","on_time":0,"next_action":{"type":-1}},{"id":"80060636AE5C93BC23D207495709446E1A9D36D804","state":0,"alias":"x5","on_time":0,"next_action":{"typ
`

**Comment by romainrobotics** [comment]
Here's the log file
[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/2752631/plugin_tplinksmartplug_debug.log)

**Comment by jneilliii** [comment]
Perfect, thanks.  I can see already that I'll need to account for a much longer response back from the device as it appears to be getting cut off part of the way through the status of the 5th plug.  It does however seem to show that of those 5 plugs, all of them were off so I do think it will be possible. However, because of the difference in communication logic, I think it would be easier/cleaner to fork this plugin to a new one specifically for strips just like I did for bulbs.

**Comment by romainrobotics** [comment]
I'm not sure if it matters, but plug 5 is the first one without anything plugged in to it.

**Comment by ridencww** [comment]
Has any further progress been made on this? I purchased a HS300 and was hoping to use it with your plugin.  For my purposes, I only need on/off and maybe status; not all of the features of the power strip (power monitoring, schedules, etc.)

I did try the p-doyle/Python-KasaSmartPowerStrip as a standalone program and I was able to control the HS300 by specifying the plug name (e.g., "Ender 3") as well as plug number.

If there was a requirement that the plug label must match the one configured in the HS300, could the plugin detect which device (HS105, HS300) it is talking to and control the HS300 using the plug label? That seems the lightest touch to get basic functionality without the need for any UI work. 

The other five plugs in the HS300 could be controlled by adding additional configurations, if desired.

How can I help?

**Comment by jneilliii** [comment]
I haven't really had much time to dedicate to plugin development lately because of work. It really is going to be a demand thing. I've just recently worked on energy monitoring and thermal runaway monitoring because there was more requests for those features. The concept of the strip is very similar to my tasmota with multiple relays. It would be easier to develop if I had a device to avoid going back and forth with testers. The energy monitoring requesters helped me get one of those devices via PayPal tips, which helped in pushing forward development.

**Comment by jneilliii** [comment]
If I could get one of you guys to install a test version of the plugin to pull some response data for me that would be great.  Use the url below in plugin manager and install the 0.9.16 version, which is what I'll be targeting for this enhancement.  Add a plug that is the ip address of your strip, enable debugging, and then restart octoprint.  If not prompted to reload the interface please force a reload and then upload your plugin_tplinksmartplug_debug.log file here. Need to see if I can pull the full response from the strip to process or not. The previous log I got was getting chopped off and I want to see if a change I just made will get around that.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.16.zip

**Comment by ridencww** [comment]
It looks promising.  I only have one plug defined at present ("Ender 3", plug 1), but the log seems to show all six plugs and the power data request afterwards.  Hope this helps.

[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3100942/plugin_tplinksmartplug_debug.log)

**Comment by jneilliii** [comment]
Perfect, thanks.  This log definitely looks like it's not getting clipped like the previous one.  I should be able to work on this with a little more confidence now. What's interesting it appears to be pulling energy data as well.  Is the power consumption data in the kasa app show data per plug or as an overall whole for the strip?

**Comment by ridencww** [comment]
The Kasa app reports energy usage by plug (in watts, and kwH,  to two decimals places). When I use API calls to report energy usage for all the plugs, all plugs report a current_ma of 4 when the plug is off while the voltage_mv varies ever so slightly (about 15 mv difference from low to high). This leads me to believe the power is reported per plug.

So, by my calculations, there is nearly 3 watts used by the plugs in the off state, not to mention the overhead of powering the actual controller electronics. That was a bit of a surprise for me. If I turn on one of the plugs, the current_ma is still 4 ma and that is with a relay actuation and LED lit. 

While puzzling, I won't have time to investigate further today and I will be away tomorrow, but I'll see if I can dig a little deeper into this next week.

Thanks for having a look at this and don't hesitate to reach out if you need anything from me.

**Comment by romainrobotics** [comment]
I can dig in a bit later on today and tomorrow afternoon.

**Comment by jneilliii** [comment]
No worries. I combed through the other python library and see where the energy data is per plug, so not sure what ther plugin is reporting on here for emeter data. Maybe the core device of the strip itself and that's what it takes to run the chip, etc.

**Comment by jneilliii** [comment]
I think I'm going to make the strip plugin a separate fork of this plugin like I did the smartbulb one simply because managing the different commands within a single plugin is too cumbersome.

**Comment by romainrobotics** [comment]
Whatever works best. Let me know if you need me to run some tests.

**Comment by ridencww** [comment]
Definitely choose the approach that makes it the easiest to maintain. Nothing says that the code couldn't be refactored in the future if other TP Link devices are introduced and it might make sense to consolidate the code.

For me, controlling the strip (printer) via Octoprint is my primary requirement, which means I need to specify which strip plug to use (either by alias or port number).  Although having access to   energy usage from the plugin would be a nice touch, I could get that information from the Kasa application.

**Comment by jneilliii** [comment]
So some quick testing with a non-strip device passing the context with the command is not detrimental, so this may be way easier to integrate than I thought.  To verify though I was wondering if one of you guys could test something with your strip.  If you download the file from softcheck [here](https://github.com/softScheck/tplink-smartplug/raw/master/tplink_smartplug.py) and run the following command replacing the ip with your strip's ip.
```
tplink_smartplug.py -t 10.0.0.60 -j {\"system\":{\"get_sysinfo\":{}},\"emeter\":{\"get_realtime\":{}}}
```
The Receive value will look something like the below.
```
"system":{"get_sysinfo":{"sw_ver":"1.0.10 Build 190103 Rel.163517","hw_ver":"1.0","model":"HS300(US)","deviceId":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F18","oemId":"5C9E6254BEBAED63B2B6102966D24C17","hwId":"34C41AA028022D0CCEA5E678E8547C54","rssi":-49,"longitude_i":-882602,"latitude_i":423195,"alias":"TP-LINK_Power Strip_1B5F","mic_type":"IOT.SMARTPLUGSWITCH","feature":"TIM:ENE","mac":"B0:BE:76:80:1B:5F","updating":0,"led_off":0,"children":[{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1800","state":0,"alias":"Ender 3","on_time":0,"next_action":{"type":-1}},{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1801","state":0,"alias":"Plug 2","on_time":0,"next_action":{"type":-1}},{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1802","state":0,"alias":"Plug 3","on_time":0,"next_action":{"type":-1}},{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1803","state":0,"alias":"Plug 4","on_time":0,"next_action":{"type":-1}},{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1804","state":0,"alias":"Plug 5","on_time":0,"next_action":{"type":-1}},{"id":"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1805","state":0,"alias":"Plug 6","on_time":0,"next_action":{"type":-1}}],"child_num":6,"err_code":0}}}
```
If you then run the following command with the child_ids replaced with the id associated with the plug from the children section above it should return the info for that individual plug.
```
tplink_smartplug.py -t 192.168.0.102 -j {\"context\":{\"child_ids\":[\"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1800\"]},\"system\":{\"get_sysinfo\":{}},\"emeter\":{\"get_realtime\":{}}}
```
@ridencww, you should be able to copy/paste those commands as I used your "Ender 3" plug as an example, so make sure you're not printing or use one of the other ids from the children section for testing.

Thanks for the help guys since I don't have a strip yet.

**Comment by ridencww** [comment]
Specifying the context works cleanly if I only specify "emeter". It reports on the plug requested using the id.

If I request "system" and "emeter", the get_sysinfo data is truncated and I see no emeter data.  If I reverse the commands "emeter" and "system", then the emeter data is fully reported, but the get_sysinfo is truncated once again.

If the plugin doesn't need both sets of data from a single call. Then, this solution seems to work.

I also tried \"system\":{\"set_relay_state\":{\"state\":1}}} and the plug turned on and \"system\":{\"set_relay_state\":{\"state\":0}}} turned the plug off.

**Comment by jneilliii** [comment]
Oh yeah, right. The data is getting truncated because that python file doesn't have my fix incorporated for that. Perfect, thanks for testing the on/off commands too. I foresee having a functional integration by the end of this weekend.

**Comment by romainrobotics** [comment]
Wow, thanks a lot. You guys are way better at this stuff than I am.

**Comment by ridencww** [comment]
Sweet! Thanks for all the hard work, I do appreciate it.

@romainrobotics it is a team effort that got us this far.

**Comment by jneilliii** [comment]
@ridencww, I'm developing a game plan for how to store the data and was wondering if you could run the following command and give me the response back using a patched version of tplink_smartplug.py [here](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/raw/0.9.16/octoprint_tplinksmartplug/tplink_smartplug.py)?

```
tplink_smartplug.py -t 10.0.0.60 -j {\"context\":{\"child_ids\":[\"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1800\"]},\"system\":{\"get_sysinfo\":{}},\"emeter\":{\"get_realtime\":{}}}
```

**Comment by ridencww** [comment]
Here you go.

[output.txt](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3123449/output.txt)

**Comment by jneilliii** [comment]
Awesome, thanks.

**Comment by jneilliii** [comment]
Does the emeter data change if you query one of the other socket deviceIds?
```
tplink_smartplug.py -t 10.0.0.60 -j {\"context\":{\"child_ids\":[\"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1801\"]},\"system\":{\"get_sysinfo\":{}},\"emeter\":{\"get_realtime\":{}}}
```

**Comment by jneilliii** [comment]
One other request.  Could you also post the response to this command please?
```
tplink_smartplug.py -t 10.0.0.60 -j {\"context\":{\"child_ids\":[\"80062D21C0AEC2B09AA1E67FDDD5C0E11AD78F1800\"]},\"system\":{\"set_relay_state\":{\"state\":1}}}

```

**Comment by ridencww** [comment]
The readings do change.  Attached are the emeter command outputs for the first three sockets (1=Ender 3/bed heating on, 2=small space heater on, 3=off). It does appear that there may be a 4 ma quiescent current per plug even if the plug is off or nothing is plugged into that plug.

[reading.txt](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3123540/reading.txt)

**Comment by jneilliii** [comment]
Thanks @ridencww.  I may have a working update that will provide basic functionality for toggling the sockets.  Only issue will be I see from your results that the strip reports emeter data similar to the EU plugs, so I'll need to tweak the logging/reporting.  This was something on my list to do anyway.  If you don't mind, please update the plugin using the url below and let me know if my assumptions are correct and that you are able to get the current status and toggle an individual plug on your strip.  Once installed open settings and update the ip address to 10.0.0.60:0.  That will be your Ender 3 plug or 10.0.0.60:1 would be the next plug over, etc.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.16.zip

The only functionality that hasn't been updated would be the countdown timer options. If it doesn't seem to work please upload your octoprint.log and plugin_tplinksmartplug_debug.log

**Comment by ridencww** [comment]
When I click the lightning icon, it attempts an emeter request instead of turn on/off. However, that request fails because the get_device_id function isn't able to obtain the id.

[2019-04-27 16:02:39,298] DEBUG: Sending command {'emeter': {'get_realtime': {}}, 'context': {'child_ids': [False]}} to 10.0.0.60
[2019-04-27 16:02:39,415] DEBUG: «  H˜"emeter":{"get_realtime":{"err_code":-3,"err_msg":"invalid argument"}}}

I made the following changes in __init__.py which allowed me to get the id from the children list and that allowed the emeter request to succeed. Although I was expecting an on/off operation when I clicked on the lightning icon.

Line 277:
response = self.deep_get(plug_data,["system","get_sysinfo","children"], default=False)
if response:
    response = response[int(plug_ip[1])]["id"]

Line 299:
return self.deep_get(d.get(keys[0]), keys[1:], default)

Could you consider changing the delimiter that specifies the plug from ":" to "/"?  Although the colon works, it is more intuitive (to me) as I see "10.0,0,60/1" as a URI and "10.0.0.60:1" as an IP and port. You can tell I do a lot of IoT things.  :)  No worries, if you rather not, 

---

I also can't add a second plug or select a plug for the graph.  Not a high priority, but I thought I would let you know that these things aren't working.

I need to hang it up for today, but if I have time tomorrow, I'll get back to this and see if I can understand how the UI interacts with the API.

**Comment by jneilliii** [comment]
I have no issue changing the delimiter, but `/` could cause some headaches on the js side possibly. How about `|` instead? Nor being able to add plugs is typically js side problems. Check the developer console in your browser for errors on initial page load/ force refresh. Probably knockout binding issues. 

Not sure why the toggle wouldn't be working unless again there was a binding problem, which would also explain the graph issue. Can you share your plugin.log

**Comment by ridencww** [comment]
I forgot to check the developer console, but I will do that tomorrow. The current debug file is attached. As you can see, the id is now able to be passed to the send command function.

I would prefer "/" or ":" over "|" though.  I don't think any of the three would be problematic with JS considering their wide use with the web (at least the first two) and are not reserved characters. But the choice isn't a big deal and I don't want to divert from getting the plugin working the way you want it to work.

[plugin_tplinksmartplug_debug.log](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3124586/plugin_tplinksmartplug_debug.log)

**Comment by jneilliii** [comment]
I just pushed an update incorporating your changes and changing the delimiter to a `/`.  As for the other stuff, I bet it's because of the emeter data units being returned by the strip.  As I mentioned earlier, the logging/reporting for emeter data needs tweaking because your strip returns voltage_mv, current_ma, power_mw, and total_wh keys where the US plugs I have return voltage, current, power, and total keys in the get_realtime dictionary value. Just need to add normalization to the python side the way I have on the JS side for the sidebar emeter data display. So my guess is what's happening is the plugin is logging a bunch of `None` values to the columns in the sqlite3 database and as a result the plotly library is failing to load properly.

**Comment by ridencww** [comment]
Thanks. I'm going to test this later today. 

I did see the issue with names of the data elements are different with the HS300 strip.  I'm thinking that I would determine which device I'm talking to (HS100 or HS300) and change the names of the data fields. If everything else goes well tonight, I may try that and let you know how that works.

**Comment by ridencww** [comment]
Using the "/" delimiter seems to work just fine.

I made a temporary change to the data fields so I could insert the rows into SQLlite (e.g., voltage -> voltage_mv and divided the values returned by 1000 (e.g., mv -> volts). I have an idea to make the necessary adaptations based on device type, which I will explore tomorrow (get the device type, create & initialize variables based on device type, and use the new variables when inserting the row).

I had to make another change to isolate the individual array element similar to the one I submitted yesterday. 

__init__.py line 223
chk = self.lookup(response,*["system","get_sysinfo","children"])
if chk:
    chk = chk[int(plug_ip[1])]["state"]

Once I made those changes, Octopi can now control the plug and the power data is graphed. We are almost there!

I can't add more plugs and get the following in the JS debug console. I will investigate further tomorrow night.

Uncaught ReferenceError: Unable to process binding "checked: function(){return thermal_runaway }"
Message: thermal_runaway is not defined
    at checked (eval at parseBindingsString (packed_libs.js?331a1bb5:11374), <anonymous>:3:60)
    at init (packed_libs.js?331a1bb5:11394)
    at packed_libs.js?331a1bb5:11378
    at Object.w (packed_libs.js?331a1bb5:11345)
    at packed_libs.js?331a1bb5:11377
    at Object.q (packed_libs.js?331a1bb5:11317)
    at m (packed_libs.js?331a1bb5:11377)
    at k (packed_libs.js?331a1bb5:11375)
    at g (packed_libs.js?331a1bb5:11375)
    at k (packed_libs.js?331a1bb5:11375)
checked @ VM19842:3
init @ packed_libs.js?331a1bb5:11394
(anonymous) @ packed_libs.js?331a1bb5:11378
...

**Comment by jneilliii** [comment]
Great. The thermal_runaway issue I think could be resolved by removing all the plugin settings in config.yaml and starting from scratch.

**Comment by jneilliii** [comment]
Actually, just realized I forgot to add that thermal_runaway key to the addplug function in the js side.

**Comment by ridencww** [comment]
Just noticed this morning that when I turn on the plug, all the plugs turn on.

I missed this before because I only was using one plug last night. It is because the set_relay_state ON command is not including context. but the OFF command does.  

It is a clever feature from TP Link to be able to switch all the plugs at once.

**Comment by jneilliii** [comment]
I just pushed the state update to the plugin along with the js fix that should resolve the binding/add plug issue.  The context is added in the sendCommand function, and the turn on command was updated along with the turn off command to send the split delimited ip, so unless you have an entry in your plugs that doesn't have a delimited entry not sure why that's happening.

**Comment by ridencww** [comment]
Thanks for the push. I'll test later today. I thought context was present on TurnOff, but that was before I had my first coffee. 

Think we're on the home stretch.

**Comment by ridencww** [comment]
One last set of changes. Refactored the db insert code to support both the HS300 strip and the other Kasa outlet that was supported before. Also found two typos, one of which caused all plugs to be turned on if any were turned on.  

I can add more plugs, control the plugs, and energy usage is logged.  I will continue testing as I use the printer. If you need me to check other components of the plugin with the HS300, let me know.

[insertChanges.txt](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/3129859/insertChanges.txt)

**Comment by jneilliii** [comment]
Thanks for the leg work.  One change I'd like you to test for me please.  If you change line 213 and beyond with the following.  This way the change will work with EU plugs, not just the strip.
```
				if self.lookup(check_emeter_data, *["emeter","get_realtime"]):
					emeter_data = check_emeter_data["emeter"]
					if emeter_data["get_realtime"]["voltage_mv"]:
						v = emeter_data["get_realtime"]["voltage_mv"] / 1000.0
					else:
						v = emeter_data["get_realtime"]["voltage"]
					if emeter_data["get_realtime"]["current_ma"]:
						c = emeter_data["get_realtime"]["current_ma"] / 1000.0
					else:
						c = emeter_data["get_realtime"]["current"]
					if emeter_data["get_realtime"]["power_mw"]:
						p = emeter_data["get_realtime"]["power_mw"] / 1000.0
					else:					
						p = emeter_data["get_realtime"]["power"]
					if emeter_data["get_realtime"]["total_wh"]:
						t = emeter_data["get_realtime"]["total_wh"] / 1000.0
					else:
						t = emeter_data["get_realtime"]["total"]
					self.db = sqlite3.connect(self.db_path)
					cursor = self.db.cursor()
					cursor.execute('''INSERT INTO energy_data(ip, timestamp, current, power, total, voltage) VALUES(?,?,?,?,?,?)''', [plugip,today.isoformat(' '),c,p,t,v])
					self.db.commit()
					self.db.close()
```

**Comment by jneilliii** [comment]
Actually, I just pushed an update that should be better. Just reinstall the 0.9.16 branch and test for me please.  This should now work with EU plugs and the strip.

**Comment by ridencww** [comment]
Good timing. I was just sitting down to look at this.  

I installed the latest code and I am able to control all six plugs and monitor/graph the energy usage.  Additionally, I have a HS105 plug downstairs that I can also control with the plugin, but it doesn't have  energy monitoring. 

The octoprint.log and plugin_tplinksmartplug_debug.log logs are clean, so I think we have a winner!

Thanks for all the help and reach out to me if you need further testing at any point.

**Comment by jneilliii** [comment]
Awesome, I'm going through and testing some final stuff relative to the tab graphs and will probably get some more testers from the energy monitoring issue before release. Thank you for all your help on this. Saved me from having to buy a strip.
