### ISSUE TITLE
Status not refreshed after G-code power off

### ISSUE THREAD

**Issue by Jozer99** [jneilliii/OctoPrint-TPLinkSmartplug#90]
I have my Octoprint setup so that the M81 command is given in the ending GCODE script, turning the printer off.  When this happens, the icon in the top bar of Octoprint remains green, and clicking it warns that the printer will be turned off.  Accepting this warning results in the lightning bolt turning red.  The expected behavior would be that the top bar icon would reflect the actual power status of the printer after a GCODE command without needing to click the icon or refresh the page.

**Comment by jneilliii** [comment]
Resolved with version 0.9.13 that I just released.
