### ISSUE TITLE
Lost of lightning icon + impossible to setup with "+" icon.

### ISSUE THREAD

**Issue by Getoval** [jneilliii/OctoPrint-TPLinkSmartplug#91]
Hello,

Until 5 or 6 days my pluggin running well.  But now (I think after an Octoprint update) I lost the lightning icon into the taskbar.
And  when I go into the "TP-Link Smartplug Settings", when I click "+" icon, nothing appens.

I tried to uninstall and re - install but not better.
I saw some "warning" with old pip version during installation.
So I made this update like description here:
https://octoprint.org/blog/2017/11/01/octopi-0.12-pip-issues/?utm_medium=announcements&utm_source=octoprint&utm_content=1.3.10

And I retried to re-install TpLink pluggin.
But when I click on the advanced "option" : "Use --process-dependency-links with pip install" I got and error...

When I unclik this option, the installation is made, but the 2 problems still.

So finally I am lost ....
Thanks for your help.

Christophe.

**Comment by jneilliii** [comment]
What version of the plugin are you running?

**Comment by jneilliii** [comment]
Any errors in octoprint.log?

**Comment by Getoval** [comment]
I installed the last one : 0.9.13

I will looking for log files ...

**Comment by Getoval** [comment]
Find enlosed extraction of octoprint log file.
From my side I don't saw error ... (except when I tried to install with "Use --process-dependency-links with pip install" option)
[Extract_Log.txt](https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/files/2873343/Extract_Log.txt)

**Comment by jneilliii** [comment]
Look in your browser's developer console for errors. You could try deleting all the settings for the plugin in config.yaml and restart octoprint and add your plug back in.

**Comment by Getoval** [comment]
I have this error into developer console:
![capture1](https://user-images.githubusercontent.com/47720606/52918969-9a65fa80-32fd-11e9-94d9-fa0faafb00d4.JPG)

![capture2](https://user-images.githubusercontent.com/47720606/52918972-a05bdb80-32fd-11e9-9ad2-07f856230726.JPG)

**Comment by jneilliii** [comment]
Yeah, I think that will get fixed if you clear out the plugin's settings in config.yaml.

**Comment by Getoval** [comment]
Hi jneilliii,

The cleaning of the file config.yaml, solved the problem.
Thanks for your time with me.

Bye.
Christophe.
