### ISSUE TITLE
TPLinkSmartPlug Plugin is Changing the Config which Causes Interface Reloads

### ISSUE THREAD

**Issue by markschabacker** [jneilliii/OctoPrint-TPLinkSmartplug#93]
The TPLinkSmartPlug plugin is changing the config:

```
pi@octopi-mk3:~/.octoprint $ ls -ltr --time-style=full-iso config.yaml*
-rw-r--r-- 1 pi pi 4370 2019-03-06 17:43:58.034429405 -0500 config.yaml-2019-03-06-17-43
-rw-r--r-- 1 pi pi 4372 2019-03-06 18:56:07.147713057 -0500 config.yaml
pi@octopi-mk3:~/.octoprint $ diff config.yaml config.yaml-2019-03-06-17-43
98c98
<           current: 1.500897
---
>           current: 1.09913
100,102c100,102
<           power: 127.945853
<           total: 36.119
<           voltage: 121.815145
---
>           power: 83.926276
>           total: 35.963
>           voltage: 122.055105
pi@octopi-mk3:~/.octoprint $
```

This change to `config.yaml` is propagating to the interface, which then is forcing a reload of the interface because of a new config hash. See foosel/OctoPrint#2950

**Comment by jneilliii** [comment]
Yeah, this is something that I've been trying to figure out how to fix.  I need to detach the current energy monitoring data from being stored in settings to prevent this.  It was something that I've done for the current on/off state, just haven't had the chance to separate the energy monitoring data.

**Comment by jneilliii** [comment]
Try installing the 0.9.14 branch by using the url in plugin manager and let me know if that is still giving you the same thing.  I just removed the settings save from the code and it appears that the energy monitoring display is still working for me on a fresh new install.

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/archive/0.9.14.zip

**Comment by markschabacker** [comment]
The code in the `0.9.14` appears to have corrected the issue for me.  Thanks!

**Comment by jneilliii** [comment]
With the caveat that the energy data never updates. I'll have to look deeper into that later in the week.

**Comment by jneilliii** [comment]
I just pushed an update to the same 0.9.14 branch that now will update the energy data in the sidebar panel during prints or with polling enabled, but I'm still not completely happy with it yet to release. I'm considering a complete re-write of the data structure on the back-end.
