### ISSUE TITLE
Option to shutdown octoprint

### ISSUE THREAD

**Issue by jimmyeao** [jneilliii/OctoPrint-TPLinkSmartplug#96]
How can I have it shutdown octoprint as well as the plug? I have a 30-sec delay on the plug, and can manually shut down octoprint once that timer has started. would be nice to do it all in one

**Comment by jneilliii** [comment]
You could use a system command option with a longer delay than the power off of `sudo service octoprint stop`. Or if you want to power off the pi completely `sudo shutdown now`.
