### ISSUE TITLE
temperature failsafe  shutting down for too low temp

### ISSUE THREAD

**Issue by overling** [jneilliii/OctoPrint-TPLinkSmartplug#99]
Running smoothieware and 2 hotend thermistors. 

tested failsafe to alarm when temp falls below 5 and tested at 10.
Both times it fails with message <5 or <10 and stops print.

set to 0 and printer runs ok.  
Temp inside it ambient reading around 24c.

**Comment by jneilliii** [comment]
@overling, what is your issue/request?  Do you want to add the temperature failsafe feature to the plugin so it will automatically turn off the plug when the temperature is below some pre-defined setting?

**Comment by overling** [comment]
HI, 
there are two settings, an over temp and an undertemp.

For some reason the undertemp is tripping when its not actually under temp.
for example when i set undertemp to stop process <10c and i start the print it will immediately stop the print in alarm.
But now i set undertemp setting to 0 and the print will run just fine.   
![image](https://user-images.githubusercontent.com/6437882/55673944-7043aa00-5863-11e9-9448-893347271802.png)

This started after updating to the previous octoprint release candidate.

**Comment by jneilliii** [comment]
My plugin doesn't have those settings, are those in some other plugin you are using to integrate with mine?

**Comment by overling** [comment]
OH man, i got linked into your git from a thread in another plugin page by accident.  Go ahead and close this please.  Also, I had to stop using your plugin some months back because it was interfering with another plugin or another plugin was interfering with yours.  I had messaged about it but you i don't know if it ever got fixed. I forgot what it was now.  anyway sorry for the mix up.
